import{PianoAudio}from'./audio.js';import{SongLibrary}from'./library.js';
const $=s=>document.querySelector(s),audio=new PianoAudio(message=>status(message)),library=new SongLibrary(),keyboard=$('#keyboard'),roll=$('#roll'),ctx=roll.getContext('2d');
const codes=['KeyZ','KeyS','KeyX','KeyD','KeyC','KeyV','KeyG','KeyB','KeyH','KeyN','KeyJ','KeyM','KeyQ','Digit2','KeyW','Digit3','KeyE','KeyR','Digit5','KeyT','Digit6','KeyY','Digit7','KeyU','KeyI','Digit9','KeyO','Digit0','KeyP','BracketLeft','Equal','BracketRight','KeyA','KeyF','KeyK','KeyL','Semicolon'];
const printed=['Z','S','X','D','C','V','G','B','H','N','J','M','Q','2','W','3','E','R','5','T','6','Y','7','U','I','9','O','0','P','[','=',']','A','F','K','L',';'];
const blacks=new Set([1,3,6,8,10]),names=['C','C♯','D','D♯','E','F','F♯','G','G♯','A','A♯','B'];
let song=null,base=60,keyCount=innerWidth<650?8:14,keyElements=new Map(),keyRects=new Map(),pointers=new Map(),downs=new Map(),playing=false,mode='free',position=0,origin=0,speed=1,nextIndex=0,groups=[],groupIndex=0,matched=new Set(),playEpoch=0,recording=false,recordStart=0,recordNotes=[],recordOwners=new Map(),results=[],pageSize=50,selectionEpoch=0,followLightUntil=0,endPrefix=[],lastDrawSignature='';
const time=ms=>`${Math.floor(ms/60000)}:${String(Math.floor(ms/1000)%60).padStart(2,'0')}`;function status(s){$('#status').textContent=s||'';}
function duration(){return song?Math.max(1,song.durationMs||song.notes.reduce((m,n)=>Math.max(m,n.start+n.duration),0)):1;}
function mapPitch(p){let x=p;const last=Math.max(...keyElements.keys());while(x<base)x+=12;while(x>last)x-=12;return keyElements.has(x)?x:null;}
function configureKeys(){releasePhysical();keyboard.replaceChildren();keyElements.clear();keyRects.clear();let whites=[],all=[],p=base;while(whites.length<keyCount&&p<=108){all.push(p);if(!blacks.has(p%12))whites.push(p);p++;}const width=100/whites.length;for(const pitch of all){const black=blacks.has(pitch%12),index=black?whites.filter(x=>x<pitch).length:whites.indexOf(pitch),left=black?index*width-width*.31:index*width;const b=document.createElement('button');b.className='key '+(black?'black':'white');b.style.left=left+'%';b.style.width=width*(black?.62:1)+'%';b.dataset.pitch=pitch;b.setAttribute('aria-label',names[pitch%12]+(Math.floor(pitch/12)-1));const label=document.createElement('span');label.className='label';const code=document.createElement('span');code.className='computer';code.textContent=printed[pitch-base]||'';const note=document.createElement('span');note.className='name';note.textContent=names[pitch%12]+(Math.floor(pitch/12)-1);label.append(code,note);b.append(label);keyboard.append(b);keyElements.set(pitch,b);}updateRects();}
function updateRects(){const area=keyboard.getBoundingClientRect();for(const[p,b]of keyElements){const r=b.getBoundingClientRect();keyRects.set(p,{left:r.left-area.left,width:r.width,black:blacks.has(p%12)});}}
function makeGroups(){groups=[];endPrefix=[];if(!song)return;let end=0;for(const n of song.notes){end=Math.max(end,n.start+n.duration);endPrefix.push(end);}for(const note of song.notes){let group=groups[groups.length-1];if(!group||Math.abs(group.start-note.start)>15){group={start:note.start,notes:[]};groups.push(group);}group.notes.push(note);}groupIndex=groups.findIndex(g=>g.start>=position);if(groupIndex<0)groupIndex=groups.length;matched.clear();}
function expected(){const g=groups[groupIndex];if(!g)return[];return $('#simple').checked?[g.notes.reduce((a,b)=>a.pitch>b.pitch?a:b)]:g.notes;}
function rangeFrom(ms){let lo=0,hi=endPrefix.length;while(lo<hi){const mid=(lo+hi)>>>1;if(endPrefix[mid]<ms)lo=mid+1;else hi=mid;}return lo;}
function activeNotes(){const found=[];for(let i=rangeFrom(position);i<song.notes.length&&song.notes[i].start<=position;i++){const n=song.notes[i];if(n.start+n.duration>position)found.push(n);}return found;}
function updateLights(){for(const b of keyElements.values())b.classList.remove('current','next','pressed');for(const x of downs.values())keyElements.get(x.mapped)?.classList.add('pressed');const notes=playing&&mode==='follow'?expected():playing&&mode==='auto'?activeNotes():[];for(const n of notes)keyElements.get(mapPitch(n.pitch))?.classList.add('current');if(playing&&mode==='follow'&&$('#preview').checked){const g=groups[groupIndex+1];if(g)keyElements.get(mapPitch(Math.max(...g.notes.map(n=>n.pitch))))?.classList.add('next');}}
function instruction(){if(!playing)return mode==='free'?'直接点击琴键，或使用电脑键盘弹奏':'准备好后点击开始';if(mode==='auto')return'自动演奏中 · 可随时暂停';if(mode==='follow'){const g=expected();if(!g.length)return'已完成';const p=mapPitch(g[0].pitch),label=printed[p-base];return ($('#simple').checked?'轻点亮键一次，自动补足音长':'按住亮键，跟随音符长度松开')+(label?' · 电脑按 '+label:'');}return'自由弹奏';}
async function playNote(id,pitch,velocity=85,start=0,length=0){const voice=await audio.on(id,pitch,velocity,start);if(voice&&length>0)audio.off(id,false,Math.max(audio.context.currentTime,start)+length/1000);}
function noteDown(owner,mapped){if(downs.has(owner)||mapped===null)return;const e=expected(),note=playing&&mode==='follow'?e.find(n=>mapPitch(n.pitch)===mapped):null,pitch=note?.pitch??mapped;downs.set(owner,{mapped,pitch});if(recording)recordOwners.set(owner,{pitch,start:Math.round(performance.now()-recordStart),velocity:85});
 if(playing&&mode==='follow'&&note){matched.add(note.pitch);if($('#simple').checked){const g=groups[groupIndex];for(const n of g.notes)playNote(`follow-${playEpoch}-${groupIndex}-${n.pitch}`,n.pitch,85,0,n.duration/speed);}else playNote(owner,pitch,85);if(e.every(n=>matched.has(n.pitch))){position=groups[groupIndex].start;followLightUntil=performance.now()+Math.max(120,note.duration/speed);groupIndex++;matched.clear();if(groupIndex>=groups.length){playing=false;position=duration();$('#start').textContent='开始';status('完成了，可以从头再弹一遍');}}}
 else playNote(owner,pitch,85);updateLights();}
function noteUp(owner){const value=downs.get(owner);if(!value)return;downs.delete(owner);audio.off(owner);const event=recordOwners.get(owner);if(event){recordOwners.delete(owner);recordNotes.push({...event,duration:Math.max(1,Math.round(performance.now()-recordStart)-event.start)});}updateLights();}
function releasePhysical(){for(const id of [...downs.keys()])noteUp(id);pointers.clear();}
function pause(){playing=false;playEpoch++;releasePhysical();audio.stop();$('#start').textContent='开始';updateLights();}
function restart(){pause();position=0;nextIndex=0;groupIndex=0;matched.clear();status('已回到开头，点击开始播放');}
async function start(){if(playing){pause();return;}if(mode==='free'){await audio.unlock();status('自由弹奏已就绪');return;}if(!song){status('先从曲库选择歌曲');$('#library').click();return;}const epoch=++playEpoch;$('#start').disabled=true;status('正在准备音色…');try{await audio.unlock();await audio.prepare(song.notes.map(n=>n.pitch));if(epoch!==playEpoch)return;if(position>=duration())position=0;nextIndex=song.notes.findIndex(n=>n.start>=position);if(nextIndex<0)nextIndex=song.notes.length;makeGroups();origin=audio.context.currentTime-position/1000/speed;playing=true;$('#start').textContent='暂停';status('');}catch(e){status(e.message);}finally{$('#start').disabled=false;}}
keyboard.addEventListener('pointerdown',e=>{const b=e.target.closest('.key');if(!b)return;e.preventDefault();keyboard.setPointerCapture(e.pointerId);const p=Number(b.dataset.pitch);pointers.set(e.pointerId,p);noteDown('pointer-'+e.pointerId,p);});keyboard.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId))return;const b=document.elementFromPoint(e.clientX,e.clientY)?.closest('.key'),p=b?Number(b.dataset.pitch):null,old=pointers.get(e.pointerId);if(old===p)return;noteUp('pointer-'+e.pointerId);pointers.set(e.pointerId,p);if(p!==null)noteDown('pointer-'+e.pointerId,p);});for(const type of['pointerup','pointercancel','lostpointercapture'])keyboard.addEventListener(type,e=>{noteUp('pointer-'+e.pointerId);pointers.delete(e.pointerId);});
const editing=target=>target?.matches?.('input,textarea,select,[contenteditable="true"]')||document.querySelector('dialog[open]');
addEventListener('keydown',e=>{if(editing(e.target)||e.ctrlKey||e.metaKey||e.altKey)return;const index=codes.indexOf(e.code);if(index>=0){e.preventDefault();if(!e.repeat&&keyElements.has(base+index))noteDown('key-'+e.code,base+index);}else if(e.code==='Space'){e.preventDefault();if(!e.repeat)start();}else if(e.code==='ArrowLeft'||e.code==='ArrowRight'){e.preventDefault();if(!e.repeat)shift(e.code==='ArrowLeft'?-12:12);}});addEventListener('keyup',e=>{if(codes.includes(e.code)){if(downs.has('key-'+e.code))e.preventDefault();noteUp('key-'+e.code);}});addEventListener('blur',()=>{releasePhysical();pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});
function shift(n){base=Math.max(24,Math.min(84,base+n));configureKeys();status('音域已调整，当前音区保持固定');}
$('#lower').onclick=()=>shift(-12);$('#higher').onclick=()=>shift(12);$('#start').onclick=start;$('#restart').onclick=restart;$('#mode').onchange=e=>{pause();mode=e.target.value;makeGroups();status('');};$('#seek').oninput=e=>{pause();position=Number(e.target.value);makeGroups();};$('#tone').onchange=e=>{releasePhysical();audio.stop();audio.tone=e.target.value;status('音色已切换');};$('#volume').oninput=e=>audio.setVolume(Number(e.target.value));$('#sustain').onchange=e=>{audio.sustain=e.target.checked;};$('#key-count').value=keyCount;$('#key-count').onchange=e=>{keyCount=Number(e.target.value);configureKeys();};$('#speed').oninput=e=>{pause();speed=Number(e.target.value);$('#speed-label').textContent=speed.toFixed(2).replace(/0+$/,'').replace(/\.$/,'')+'×';};$('#simple').onchange=()=>{matched.clear();updateLights();};$('#preview').onchange=updateLights;
for(const b of document.querySelectorAll('[data-close]'))b.onclick=()=>b.closest('dialog').close();function open(id){pause();$(id).showModal();}$('#settings').onclick=()=>open('#settings-dialog');$('#help').onclick=()=>open('#help-dialog');
async function choose(row){const epoch=++selectionEpoch;pause();status('正在加载曲谱…');try{const selected=await library.load(row);if(epoch!==selectionEpoch)return;song=selected;position=0;nextIndex=0;makeGroups();$('#song-title').textContent=song.title;$('#library-dialog').close();if(mode==='free'){mode='follow';$('#mode').value=mode;}status(song.storageWarning||'曲谱已就绪，点击开始');audio.fetchSample(Math.max(...song.notes.slice(0,8).map(n=>n.pitch))).catch(()=>{});}catch(e){status(e.message);}}
function list(){results=library.search($('#search').value,$('#category').value);$('#songs').replaceChildren();for(const row of results.slice(0,pageSize)){const wrap=document.createElement('div');wrap.className='song-row';const b=document.createElement('button'),title=document.createElement('span'),meta=document.createElement('small');title.textContent=row.title;meta.textContent=[row.category,row.author||row.subtitle,time(row.durationMs||0)].filter(Boolean).join(' · ');b.append(title,meta);b.onclick=()=>choose(row);const fav=document.createElement('button');fav.className='fav';fav.textContent=library.favorites.has(row.id)?'★':'☆';fav.setAttribute('aria-label','收藏 '+row.title);fav.onclick=()=>{library.favorite(row.id);list();};wrap.append(b,fav);$('#songs').append(wrap);}$('#library-status').textContent=`${results.length.toLocaleString()} 个结果${library.catalog?' · 原有可用曲谱快照，选择后才加载音符':''}`;$('#more').hidden=results.length<=pageSize;}
$('#library').onclick=async()=>{open('#library-dialog');await library.builtins;list();try{await library.all();for(const category of [...new Set(library.catalog.entries.map(s=>s.category))]){if([...$('#category').options].some(o=>o.value===category))continue;const o=new Option(category,category);$('#category').append(o);}list();}catch(e){$('#library-status').textContent=e.message+'；内置曲目与导入仍可使用';}};$('#search').oninput=()=>{pageSize=50;list();};$('#category').onchange=()=>{pageSize=50;list();};$('#more').onclick=()=>{pageSize+=50;list();};$('#import').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{const s=await library.import(file);list();await choose(s);}catch(error){$('#library-status').textContent=error.message;}e.target.value='';};
function download(name,body,type='application/json'){const u=URL.createObjectURL(new Blob([body],{type})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
$('#record').onclick=async()=>{if(!recording){await audio.unlock();pause();recordNotes=[];recordStart=performance.now();recording=true;$('#record').textContent='■ 停止录制';status('正在录制你的弹奏');}else{releasePhysical();recording=false;$('#record').textContent='● 录制';if(!recordNotes.length){status('还没有录到音符');return;}recordNotes.sort((a,b)=>a.start-b.start||a.pitch-b.pitch);const s={id:'record-'+Date.now(),title:'我的演奏 '+new Date().toLocaleTimeString(),bpm:120,notes:recordNotes,durationMs:recordNotes.reduce((m,n)=>Math.max(m,n.start+n.duration),0),noteCount:recordNotes.length};try{library.save(s);status(s.storageWarning||'已保存在我的曲目，并导出弹奏文件');}catch(_){status('本机存储空间不足，弹奏已导出为文件');}download('我的演奏.json',JSON.stringify(s));}};
function notation(n){const pitch=n.pitch%12,degrees={0:'1',2:'2',4:'3',5:'4',7:'5',9:'6',11:'7'},value=degrees[pitch]||'♯'+degrees[(pitch+11)%12],oct=Math.floor(n.pitch/12)-5;return(oct>0?'˙'.repeat(oct):'')+value+(oct<0?'̣'.repeat(-oct):'');}
function scoreText(){if(!song)return'先选择一首歌曲';let text=song.title+'\n\n';for(let i=0;i<groups.length;i++){const g=groups[i];text+=(g.notes.length>1?'['+g.notes.map(notation).join(' ')+']':notation(g.notes[0]))+' ';if((i+1)%8===0)text+='\n';}return text;}
$('#score').onclick=()=>{$('#score-content').textContent=scoreText();open('#score-dialog');};$('#save-score').onclick=()=>download((song?.title||'曲谱')+'-简谱.txt',scoreText(),'text/plain;charset=utf-8');
function draw(){const w=roll.clientWidth,h=roll.clientHeight,d=Math.min(2,devicePixelRatio||1);if(roll.width!==Math.round(w*d)||roll.height!==Math.round(h*d)){roll.width=Math.round(w*d);roll.height=Math.round(h*d);updateRects();}const signature=[w,h,d,base,keyCount,song?.id,mode,position,groupIndex,playing].join('|');if(signature!==lastDrawSignature){lastDrawSignature=signature;ctx.setTransform(d,0,0,d,0,0);ctx.clearRect(0,0,w,h);const sx=w/keyboard.clientWidth;for(const[p,r]of keyRects){ctx.strokeStyle=r.black?'#82adbc12':'#abcbd51b';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo((r.left+r.width/2)*sx,0);ctx.lineTo((r.left+r.width/2)*sx,h);ctx.stroke();}const line=h-42;ctx.strokeStyle='#b6dbe744';ctx.beginPath();ctx.moveTo(0,line);ctx.lineTo(w,line);ctx.stroke();
 if(song&&mode!=='free'){const now=playing&&mode==='follow'?(groups[groupIndex]?.start??duration()):position,windowMs=3200;let shown=0;for(let i=rangeFrom(now-200);i<song.notes.length;i++){const n=song.notes[i];if(n.start>now+windowMs)break;if(n.start+n.duration<now-200)continue;if(++shown>350)break;const p=mapPitch(n.pitch),r=keyRects.get(p);if(!r)continue;const x=(r.left+r.width*.1)*sx,width=r.width*.8*sx,y=line-(n.start-now)/windowMs*line,height=Math.max(9,n.duration/windowMs*line);const grad=ctx.createLinearGradient(x,y-height,x,y);grad.addColorStop(0,'#73b6ce88');grad.addColorStop(1,'#a0dcece6');ctx.fillStyle=grad;ctx.beginPath();ctx.roundRect(x,y-height,width,height,Math.min(5,width/3));ctx.fill();ctx.fillStyle='#163447';ctx.font='600 11px system-ui';ctx.textAlign='center';if(width>22&&height>17)ctx.fillText(printed[p-base]||names[n.pitch%12],x+width/2,y-6);}}else{ctx.textAlign='center';ctx.font='600 '+(w<500?20:30)+'px system-ui';ctx.fillStyle='#a1bccd66';ctx.fillText('让音乐，从指尖开始',w/2,h*.43);ctx.font='12px system-ui';ctx.fillStyle='#9eb9c166';ctx.fillText('触摸 · 鼠标 · 电脑键盘',w/2,h*.43+28);}ctx.textAlign='left';}$('#instruction').textContent=instruction();$('#time').textContent=time(position);$('#duration').textContent=time(duration());$('#seek').max=duration();$('#seek').value=position;updateLights();requestAnimationFrame(draw);}
setInterval(()=>{if(!playing||mode!=='auto'||!audio.context)return;position=(audio.context.currentTime-origin)*1000*speed;const cutoff=position+100*speed,epoch=playEpoch;while(nextIndex<song.notes.length&&song.notes[nextIndex].start<=cutoff){const index=nextIndex++,n=song.notes[index],when=origin+n.start/1000/speed;playNote(`auto-${epoch}-${index}`,n.pitch,85,when,n.duration/speed);}if(position>=duration()+250){pause();position=duration();status('播放完成');}},25);
configureKeys();draw();audio.fetchSample(60).catch(()=>{});library.builtins.catch(e=>status(e.message));addEventListener('resize',updateRects);
window.PianoWeb={inspect(){return{song:song?.id||null,mode,playing,position,base,keyCount,downOwners:[...downs.keys()],audio:audio.inspect(),groupIndex,groupCount:groups.length,catalogCount:library.catalog?.count||0,cachePacks:library.cache.size,recording};},audio,library};
