/* Own mixer adapter; original CC-BY3 Alexander Holm samples, same source PCM
 * as Android. Voice owners keep keyboard, pointer and score releases separate. */
export class PianoAudio{
 constructor(onStatus=()=>{}){this.context=null;this.master=null;this.voices=new Map();this.bytes=new Map();this.buffers=new Map();this.tone='piano';this.volume=.65;this.sustain=true;this.onStatus=onStatus;this.stats={started:0,released:0,sampleVoices:0,synthVoices:0};}
 contextForGesture(){if(!this.context){const A=window.AudioContext||window.webkitAudioContext;if(!A)throw Error('浏览器不支持网页音频，请使用新版浏览器');this.context=new A({latencyHint:'interactive'});this.master=this.context.createGain();this.master.gain.value=this.volume;const limiter=this.context.createDynamicsCompressor();limiter.threshold.value=-16;limiter.ratio.value=8;this.master.connect(limiter);limiter.connect(this.context.destination);}return this.context;}
 async unlock(){const c=this.contextForGesture();if(c.state==='suspended')await c.resume();return c;}
 samplePitch(p){return Math.max(21,Math.min(108,21+3*Math.round((p-21)/3)));}
 async fetchSample(p){p=this.samplePitch(p);if(!this.bytes.has(p)){const promise=(async()=>{const controller=new AbortController(),t=setTimeout(()=>controller.abort(),12000);try{const r=await fetch(`assets/piano/${String(p).padStart(3,'0')}.bin`,{signal:controller.signal});if(!r.ok)throw Error('钢琴音色加载失败');return await r.arrayBuffer();}finally{clearTimeout(t);}})();this.bytes.set(p,promise);promise.catch(()=>this.bytes.delete(p));}return this.bytes.get(p);}
 async prepare(pitches){const c=this.contextForGesture();await Promise.all([...new Set(pitches.map(p=>this.samplePitch(p)))].map(async p=>{if(!this.buffers.has(p)){const promise=this.fetchSample(p).then(b=>c.decodeAudioData(b.slice(0)));this.buffers.set(p,promise);promise.catch(()=>this.buffers.delete(p));}await this.buffers.get(p);}));}
 setVolume(v){this.volume=Math.max(0,Math.min(1,v));if(this.master)this.master.gain.setTargetAtTime(this.volume,this.context.currentTime,.02);}
 async on(id,pitch,velocity=90,scheduled=0){if(this.voices.has(id))return;const voice={id,pitch,pending:true,nodes:[],gain:null,ended:false};this.voices.set(id,voice);if(this.voices.size>96)this.off(this.voices.keys().next().value,true);try{const c=await this.unlock();let buffer;if(['piano','soft','bright'].includes(this.tone)){try{await this.prepare([pitch]);buffer=await this.buffers.get(this.samplePitch(pitch));}catch(e){this.onStatus('钢琴采样暂未加载，使用轻柔电子音；可重新选择音色重试');}}
 if(this.voices.get(id)!==voice)return;voice.pending=false;const when=Math.max(c.currentTime,scheduled),g=c.createGain();g.connect(this.master);voice.gain=g;const level=(buffer?.25:.095)*Math.max(.12,Math.min(1,velocity/127))*(this.tone==='soft'?.65:1);g.gain.setValueAtTime(0,when);g.gain.linearRampToValueAtTime(level,when+.008);
 if(buffer){const s=c.createBufferSource();s.buffer=buffer;s.playbackRate.value=2**((pitch-this.samplePitch(pitch))/12);const filter=c.createBiquadFilter();filter.type='lowpass';filter.frequency.value=this.tone==='soft'?2600:this.tone==='bright'?11000:7000;s.connect(filter);filter.connect(g);voice.nodes=[s];s.start(when);this.stats.sampleVoices++;}
 else{const freq=440*2**((pitch-69)/12),partials=this.tone==='bell'?[[1,.8],[2.76,.25],[5.4,.1]]:this.tone==='ep'?[[1,.8],[2,.18],[3,.07]]:[[1,1]];for(const [ratio,amp]of partials){const s=c.createOscillator(),mix=c.createGain();s.frequency.value=freq*ratio;s.type=this.tone==='retro'?'square':this.tone==='pluck'?'triangle':this.tone==='organ'?'sine':'sine';mix.gain.value=amp;s.connect(mix);mix.connect(g);s.start(when);voice.nodes.push(s);}if(['bell','pluck','ep'].includes(this.tone))g.gain.exponentialRampToValueAtTime(Math.max(.0001,level*.22),when+(this.tone==='bell'?2:.8));this.stats.synthVoices++;}
 voice.nodes[0].onended=()=>{if(this.voices.get(id)===voice)this.voices.delete(id);for(const n of voice.nodes)n.disconnect();g.disconnect();};this.stats.started++;return voice;
 }catch(e){if(this.voices.get(id)===voice)this.voices.delete(id);this.onStatus(e.message);}}
 off(id,immediate=false,scheduled=0){const v=this.voices.get(id);if(!v)return;if(scheduled>this.context?.currentTime+.01){clearTimeout(v.timer);v.timer=setTimeout(()=>this.off(id,immediate),Math.max(0,(scheduled-this.context.currentTime)*1000));return;}clearTimeout(v.timer);this.voices.delete(id);this.stats.released++;if(v.pending)return;const c=this.context,t=c.currentTime,tail=immediate?.025:this.sustain?.30:.09;v.gain.gain.cancelScheduledValues(t);v.gain.gain.setTargetAtTime(.0001,t,tail/4);for(const n of v.nodes){try{n.stop(t+tail)}catch(_){}}}
 stop(){for(const id of [...this.voices.keys()])this.off(id,true);}
 inspect(){return{voices:this.voices.size,context:this.context?.state||'uninitialized',volume:this.volume,...this.stats};}
}
