export const normalize=s=>String(s||'').normalize('NFKC').toLocaleLowerCase().replace(/[\p{P}\p{S}\s]+/gu,'');
const hot=['晴天','夜曲','花之舞','flowerdance','梦中的婚礼','riverflowsinyou','起风了','稻香','告白气球','卡农','天空之城','千与千寻','summer','rush','callofsilence','你的名字','周杰伦'];
const hash=async bytes=>[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(x=>x.toString(16).padStart(2,'0')).join('');
function decodePCS(bytes,row){let at=4,start=0;const u8=()=>{if(at>=bytes.length)throw Error('曲谱数据不完整');return bytes[at++];};const variable=max=>{let n=0,f=1;for(let i=0;i<5;i++){const b=u8();n+=(b&127)*f;if(n>max)throw Error('曲谱超出安全范围');if(!(b&128))return n;f*=128;}throw Error('曲谱数字无效');};if(String.fromCharCode(...bytes.subarray(0,4))!=='PCS1')throw Error('不支持的曲谱格式');const bpm=variable(1000),count=variable(100000);if(!bpm||count>(bytes.length-at)/4)throw Error('曲谱头部无效');const notes=[];for(let i=0;i<count;i++){const pitch=u8(),velocity=u8();start+=variable(1800000);const duration=variable(1800000);if(pitch>127||!velocity||velocity>127||!duration||start+duration>1800000)throw Error('曲谱音符无效');notes.push({pitch,velocity,start,duration});}if(at!==bytes.length)throw Error('曲谱末尾数据无效');return{...row,bpm,notes};}
export class SongLibrary{
 constructor(){this.rows=[];this.catalog=null;this.loading=null;this.cache=new Map();this.details=new Map();this.packs=new Map();this.custom=[];this.favorites=new Set();try{this.custom=JSON.parse(localStorage.getItem('piano-web-songs')||'[]');this.favorites=new Set(JSON.parse(localStorage.getItem('piano-web-favorites')||'[]').map(id=>/^eop-[a-f0-9]{64}$/.test(id)?id.slice(0,20):id));}catch(_){}this.builtins=fetch('assets/builtin.json').then(r=>{if(!r.ok)throw Error('内置曲库加载失败');return r.json()}).then(rows=>{this.rows=rows.map(s=>({...s,category:'内置',subtitle:s.subtitle||'',durationMs:s.notes.reduce((m,n)=>Math.max(m,n.start+n.duration),0),noteCount:s.notes.length}));return this.rows;});}
 async all(){await this.builtins;if(this.catalog)return this.catalog;if(!this.loading)this.loading=(async()=>{const r=await fetch('assets/catalog.json.gz');if(!r.ok)throw Error('曲库加载失败，请重试');const data=window.fflate.gunzipSync(new Uint8Array(await r.arrayBuffer()));if(data.length>16000000)throw Error('曲库过大');const c=JSON.parse(new TextDecoder().decode(data));if(c.count!==c.entries.length||c.count>30000)throw Error('曲库目录无效');this.catalog=c;for(const p of c.packs)this.packs.set(p.name,p);return c;})().catch(e=>{this.loading=null;throw e;});return this.loading;}
 search(query='',category='全部'){const q=normalize(query),rows=[...this.custom,...this.rows,...(this.catalog?.entries||[])];return rows.filter(s=>(!q||normalize(s.title+' '+(s.author||'')).includes(q))&&(category==='全部'||category==='收藏'&&this.favorites.has(s.id)||category==='我的'&&s.category==='我的'||s.category===category)).sort((a,b)=>{const rank=s=>this.favorites.has(s.id)?-100:hot.findIndex(x=>normalize(s.title).includes(normalize(x)));const ar=rank(a),br=rank(b);return(ar===-1?100:ar)-(br===-1?100:br)||a.title.localeCompare(b.title,'zh-CN');});}
 async load(row){if(row.notes)return row;if(!row.entry){const p=this.packs.get(row.pack);if(!p||!/^pack-\d{4}\.json\.gz$/.test(p.detail))throw Error('Invalid song detail path');let rows=this.details.get(row.pack);if(!rows){const response=await fetch('assets/details/'+p.detail);if(!response.ok)throw Error('Song detail download failed');const bytes=new Uint8Array(await response.arrayBuffer());if(bytes.length!==p.detailBytes||await hash(bytes)!==p.detailSha256)throw Error('Song detail integrity failed');const unpacked=window.fflate.gunzipSync(bytes);if(unpacked.length>2000000)throw Error('Song detail exceeds limit');rows=JSON.parse(new TextDecoder().decode(unpacked));if(rows.length!==p.entryCount)throw Error('Invalid song detail count');this.details.set(row.pack,rows);while(this.details.size>2)this.details.delete(this.details.keys().next().value);}const detail=rows[row.slot];if(!detail||detail.id.slice(0,20)!==row.id||detail.pack!==row.pack)throw Error('Song detail mismatch');row={...detail,...row};}if(!/^pack-\d{4}\.ppack$/.test(row.pack)||!/^[a-f0-9]{40}\.pcs$/.test(row.entry))throw Error('曲库文件路径无效');let bytes=this.cache.get(row.pack);if(!bytes){const r=await fetch('assets/offline/'+row.pack);if(!r.ok)throw Error('曲谱下载失败，请重试');bytes=new Uint8Array(await r.arrayBuffer());const p=this.packs.get(row.pack);if(!p||bytes.length!==p.byteSize||await hash(bytes)!==p.sha256)throw Error('曲谱分包校验失败');this.cache.set(row.pack,bytes);while(this.cache.size>2)this.cache.delete(this.cache.keys().next().value);}const result=window.fflate.unzipSync(bytes,{filter:f=>f.name===row.entry&&f.originalSize<=1536000}),pcs=result[row.entry];if(!pcs||await hash(pcs)!==row.compactSha256)throw Error('曲谱内容校验失败');return decodePCS(pcs,row);}
 favorite(id){if(this.favorites.has(id))this.favorites.delete(id);else this.favorites.add(id);try{localStorage.setItem('piano-web-favorites',JSON.stringify([...this.favorites]));}catch(_){}return this.favorites.has(id);}
 save(song){song.category='我的';this.custom=this.custom.filter(s=>s.id!==song.id);this.custom.unshift(song);this.custom=this.custom.slice(0,30);try{localStorage.setItem('piano-web-songs',JSON.stringify(this.custom));delete song.storageWarning;}catch(_){song.storageWarning='\u6d4f\u89c8\u5668\u5b58\u50a8\u7a7a\u95f4\u4e0d\u8db3\uff0c\u672c\u6b21\u4ecd\u53ef\u6f14\u594f\uff1b\u5237\u65b0\u540e\u9700\u91cd\u65b0\u5bfc\u5165';}return song;}
 async import(file){if(file.size>8*1024*1024)throw Error('文件请小于8 MB');let song;if(/\.midi?$/i.test(file.name)){const m=new window.Midi(await file.arrayBuffer());const notes=m.tracks.flatMap(t=>t.notes.map(n=>({pitch:n.midi,velocity:Math.max(1,Math.round(n.velocity*127)),start:Math.round(n.time*1000),duration:Math.max(1,Math.round(n.duration*1000))}))).sort((a,b)=>a.start-b.start||a.pitch-b.pitch);song={id:'import-'+Date.now(),title:m.name||file.name.replace(/\.midi?$/i,''),bpm:Math.round(m.header.tempos[0]?.bpm||120),notes};}else song=JSON.parse(await file.text());if(!song||!Array.isArray(song.notes)||!song.notes.length||song.notes.length>100000)throw Error('没有可用音符');for(const n of song.notes)if(!Number.isInteger(n.pitch)||n.pitch<0||n.pitch>127||!Number.isFinite(n.start)||!Number.isFinite(n.duration)||n.start<0||n.duration<1||n.start+n.duration>1800000)throw Error('音符范围无效');song.id='import-'+Date.now();song.title=String(song.title||file.name).slice(0,120);song.notes.sort((a,b)=>a.start-b.start||a.pitch-b.pitch);song.durationMs=song.notes.reduce((m,n)=>Math.max(m,n.start+n.duration),0);song.noteCount=song.notes.length;return this.save(song);}
}
