(function(){
 'use strict';
 const $=s=>document.querySelector(s), KEY='resume-studio-web-demo-v1', clone=v=>JSON.parse(JSON.stringify(v));
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const pathIcons={document:'<path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><path d="M14 2v6h6M8 13h8M8 17h6"/>',edit:'<path d="m16 3 5 5-12 12-6 1 1-6Z"/><path d="m14 5 5 5"/>',grid:'<rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/>',eye:'<path d="M2 12s3-7 10-7 10 7 10 7-3 7-10 7S2 12 2 12Z"/><circle cx="12" cy="12" r="3"/>',folder:'<path d="M3 7V5a2 2 0 0 1 2-2h5l2 3h7a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2Z"/>',plus:'<path d="M12 5v14M5 12h14"/>',chevron:'<path d="m9 5 7 7-7 7"/>',down:'<path d="m6 9 6 6 6-6"/>',up:'<path d="m6 15 6-6 6 6"/>',close:'<path d="m6 6 12 12M6 18 18 6"/>',check:'<path d="m5 12 4 4L19 6"/>',download:'<path d="M12 3v12m-5-5 5 5 5-5M4 17v4h16v-4"/>',upload:'<path d="M12 16V3m-5 5 5-5 5 5M4 17v4h16v-4"/>',star:'<path d="m12 3 2.8 5.7 6.2.9-4.5 4.4 1.1 6.2-5.6-3-5.6 3 1.1-6.2L3 9.6l6.2-.9Z"/>',search:'<circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/>',photo:'<rect x="3" y="3" width="18" height="18" rx="3"/><circle cx="8" cy="8" r="1.5"/><path d="m21 15-5-5L5 21"/>',trash:'<path d="M3 6h18M9 6V3h6v3M6 6l1 15h10l1-15M10 10v7M14 10v7"/>',copy:'<rect x="8" y="8" width="13" height="13" rx="2"/><path d="M16 8V3H3v13h5"/>',share:'<circle cx="18" cy="5" r="3"/><circle cx="6" cy="12" r="3"/><circle cx="18" cy="19" r="3"/><path d="m8.6 10.5 6.8-4M8.6 13.5l6.8 4"/>',message:'<path d="M21 11a8 8 0 0 1-8 8H8l-5 3 1-6a8 8 0 0 1-1-5 9 9 0 0 1 18 0Z"/><path d="M8 10h8M8 14h5"/>',settings:'<path d="M4 6h16M4 12h16M4 18h16"/><circle cx="8" cy="6" r="2"/><circle cx="16" cy="12" r="2"/><circle cx="10" cy="18" r="2"/>',shield:'<path d="m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6Z"/><path d="m8 12 3 3 5-6"/>',info:'<circle cx="12" cy="12" r="9"/><path d="M12 11v6M12 7v1"/>',more:'<circle cx="5" cy="12" r="1"/><circle cx="12" cy="12" r="1"/><circle cx="19" cy="12" r="1"/>',briefcase:'<rect x="3" y="7" width="18" height="14" rx="2"/><path d="M8 7V3h8v4M3 12h18M10 12v3h4v-3"/>'};
 function icon(name,size=20){return '<svg width="'+size+'" height="'+size+'" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'+(pathIcons[name]||pathIcons.document)+'</svg>';}
 const sections=[['basics','基本信息'],['work','工作经历'],['education','教育经历'],['projects','项目经历'],['skills','技能'],['certificates','证书'],['languages','语言'],['awards','奖项'],['interests','兴趣'],['custom','自定义']];
 const sectionNames={summary:'个人简介',work:'工作经历',education:'教育经历',projects:'项目经历',skills:'技能',certificates:'证书',languages:'语言',awards:'奖项',interests:'兴趣',custom:'自定义'};
 const defaults={fontSize:12,lineHeight:1.55,margin:32,pageTarget:1,autoFit:true,photoEnabled:true,photoShape:'square',sectionOrder:Object.keys(sectionNames),hiddenSections:[],accentOverride:null};
 const forms={
  work:[['name','公司／单位','例如：某某科技有限公司'],['position','岗位','例如：产品运营'],['startDate','开始时间','2023.07'],['endDate','结束时间','至今'],['summary','工作内容与成果','说明职责、做法及结果；尽量写出可核实的成果','area']],
  education:[['institution','学校','学校全称'],['area','专业','例如：计算机科学'],['studyType','学历','例如：本科'],['score','成绩／绩点','选填'],['startDate','入学时间','2020.09'],['endDate','毕业时间','2024.06'],['summary','补充说明','相关课程、在校经历等','area']],
  projects:[['name','项目名称','例如：校园二手交易平台'],['url','项目链接','选填'],['startDate','开始时间','2024.03'],['endDate','结束时间','2024.06'],['description','项目介绍与个人贡献','说明目标、你的职责、技术或方法，以及成果','area']],
  skills:[['name','技能类别','例如：设计工具'],['level','掌握程度','例如：熟练'],['keywords','具体技能','用逗号或换行分隔，例如：Figma、Photoshop','area','array']],
  certificates:[['name','证书名称','例如：大学英语六级'],['issuer','颁发机构','选填'],['date','取得时间','2024.06'],['url','验证链接','选填']],
  languages:[['language','语言','例如：英语'],['fluency','熟练程度','例如：CET-6／日常交流']],
  awards:[['title','奖项名称','例如：优秀毕业生'],['awarder','授予单位','选填'],['date','获得时间','2024.06'],['summary','说明','选填','area']],
  interests:[['name','兴趣类别','例如：运动'],['keywords','内容','用逗号分隔，例如：游泳、羽毛球','area','array']],
  custom:[['title','栏目标题','例如：志愿服务'],['content','栏目内容','填写想展示的内容','area']]
 };
 let state,screen='editor',module='basics',category='全部',query='',visibleCount=24,saveTimer,toastTimer,busyTimer,saveOk=true,pendingImport=null,photoSource=null,modalActive=false,previewMode='auto',previewSample=null;
 const uid=()=>Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,8);
 const getEngine=()=>window.ResumeEngine;
 function sanitizeSettings(s){const out=clone(defaults);if(!s||typeof s!=='object')return out;out.fontSize=Math.min(16,Math.max(9,+s.fontSize||12));out.lineHeight=Math.min(2,Math.max(1.2,+s.lineHeight||1.55));out.margin=Math.min(56,Math.max(18,+s.margin||32));out.pageTarget=+s.pageTarget===2?2:1;out.autoFit=s.autoFit!==false;out.photoEnabled=s.photoEnabled!==false;out.photoShape=['square','circle'].includes(s.photoShape)?s.photoShape:'square';out.accentOverride=/^#[\da-f]{6}$/i.test(s.accentOverride)?s.accentOverride:null;out.hiddenSections=(Array.isArray(s.hiddenSections)?s.hiddenSections:[]).filter(x=>sectionNames[x]);const order=(Array.isArray(s.sectionOrder)?s.sectionOrder:[]).filter(x=>sectionNames[x]);out.sectionOrder=[...new Set([...order,...Object.keys(sectionNames)])];return out;}
 function newRecord(profile,title='我的简历'){return {id:uid(),title,profile:profile||ResumeImport.blank(),templateId:'t0001',settings:clone(defaults),updatedAt:Date.now()};}
 function load(){
  let raw='';try{raw=window.Native&&typeof Native.readState==='function'?Native.readState():localStorage.getItem(KEY);}catch(_){}
  try{
   const data=JSON.parse(raw||'{}');state={version:1,resumes:[],currentId:data.currentId,favorites:Array.isArray(data.favorites)?data.favorites.filter(x=>/^t\d{4}$/.test(x)).slice(0,1000):[],welcomeSeen:!!data.welcomeSeen,diagnosticsEnabled:data.diagnosticsEnabled!==false,feedback:Array.isArray(data.feedback)?data.feedback.slice(-40):[]};
   for(const r of (Array.isArray(data.resumes)?data.resumes:[]).slice(0,50)){try{state.resumes.push({id:typeof r.id==='string'?r.id:uid(),title:typeof r.title==='string'?r.title.slice(0,80):'我的简历',profile:ResumeImport.normalize(r.profile),templateId:getEngine().templates.some(t=>t.id===r.templateId)?r.templateId:'t0001',settings:sanitizeSettings(r.settings),updatedAt:+r.updatedAt||Date.now()});}catch(_){}}
  }catch(_){state={version:1,resumes:[],favorites:[],welcomeSeen:false,diagnosticsEnabled:true,feedback:[]};toast('资料文件暂时无法读取，可在“我的”恢复备份。');}
  if(!state.resumes.length){const r=newRecord();state.resumes=[r];state.currentId=r.id;}
  if(!state.resumes.some(r=>r.id===state.currentId))state.currentId=state.resumes[0].id;
 }
 function current(){return state.resumes.find(r=>r.id===state.currentId)||state.resumes[0];}
 // Preview-only content never enters state, backups, or the PDF export record.
 function hasProfileData(profile=current().profile){
  const filled=value=>typeof value==='string'?value.trim().length>0:Array.isArray(value)?value.some(filled):value&&typeof value==='object'?Object.values(value).some(filled):typeof value==='number'&&Number.isFinite(value)&&value!==0;
  return filled(profile);
 }
 function previewSource(mode=previewMode){return mode==='sample'||mode==='mine'?mode:hasProfileData()?'mine':'sample';}
 function exampleProfile(){
  if(previewSample)return previewSample;
  const p=clone(getEngine().sampleProfile);
  p.basics.summary='虚构示例资料。擅长用户需求整理、活动策划与数据分析，注重团队协作和产品体验。';
  p.work=p.work.slice(0,1);p.work[0].highlights=p.work[0].highlights.slice(0,2);
  p.education[0].summary='主修数据分析、项目管理与用户研究。';
  p.projects[0].highlights=p.projects[0].highlights.slice(0,1);
  p.skills=p.skills.slice(0,2);p.awards=[];p.interests=[];
  const canvas=document.createElement('canvas');canvas.width=180;canvas.height=240;
  const ctx=canvas.getContext('2d');if(ctx){ctx.fillStyle='#e7eef8';ctx.fillRect(0,0,180,240);ctx.fillStyle='#849aba';ctx.beginPath();ctx.arc(90,76,36,0,Math.PI*2);ctx.fill();ctx.fillStyle='#536e95';ctx.beginPath();ctx.ellipse(90,219,76,92,0,0,Math.PI*2);ctx.fill();p.basics.image=canvas.toDataURL('image/png');}
  previewSample=p;return p;
 }
 function previewRecord(source,context='preview'){
  const r=current(),settings=source==='sample'&&context==='template'?{...clone(defaults),pageTarget:r.settings.pageTarget}:clone(r.settings);
  if(context==='template')settings.accentOverride=null;
  return {id:source==='sample'?'preview-example':r.id,updatedAt:source==='sample'?0:r.updatedAt,profile:source==='sample'?exampleProfile():r.profile,settings};
 }
 function previewPicker(source,context='preview',templateId=current().templateId){return '<div class="preview-source-picker" role="group" aria-label="预览内容">'+[['sample','示例效果'],['mine','我的资料']].map(([value,label])=>button(label,'preview-source','source-tab '+(source===value?'active':''),'data-source="'+value+'" data-preview-context="'+context+'" data-id="'+esc(templateId)+'" aria-pressed="'+(source===value)+'"')).join('')+'</div>';}
 function previewNotice(source){return source==='sample'?'<div class="preview-notice" data-preview-notice><strong>虚构示例 · 仅用于看样式</strong><span>不会写入你的资料，填写或导入后会自动套入。</span></div>':!hasProfileData()?'<div class="preview-notice" data-preview-notice><strong>你的资料还是空的</strong><span>先用“示例效果”看完整样式，或填写自己的资料。</span></div>':'';}
 function openTemplate(id,mode='auto'){
  const t=getEngine().templates.find(t=>t.id===id);if(!t)return;
  const source=previewSource(mode),r=previewRecord(source,'template');
  openModal(t.name,'<p>'+esc(t.familyName)+' · '+esc(t.paletteName)+' · '+esc(t.category)+'</p>'+previewPicker(source,'template',id)+previewNotice(source)+'<div class="preview-wrap">'+iframeMarkup(getEngine().html(r.profile,t.id,r.settings),'template-frame',false,t.id,source,'template')+'</div>',button('再看看','close-modal','btn ghost')+button('使用这款模板','template-use','btn','data-id="'+t.id+'"'));
 }
 function savedStatus(){const el=$('#save-status');if(el){el.innerHTML=icon(saveOk?'check':'info',12)+(saveOk?'已保存到本机':'未保存，请备份');el.classList.toggle('error',!saveOk);}}
 function save(){clearTimeout(saveTimer);try{const data=JSON.stringify(state);if(window.Native&&typeof Native.writeState==='function'){if(!Native.writeState(data))throw Error('save');}else localStorage.setItem(KEY,data);saveOk=true;}catch(_){saveOk=false;toast('本机保存失败，请先导出备份，避免关闭后丢失。',6000);}savedStatus();return saveOk;}
 function changed(){current().updatedAt=Date.now();clearTimeout(saveTimer);saveTimer=setTimeout(save,350);updateCompletion();}
 function toast(msg,duration=2800){const el=$('#toast');if(!el)return;el.textContent=msg;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),duration);}
 function button(label,action,style='btn',extra=''){return '<button type="button" class="'+style+'" data-action="'+action+'" '+extra+'>'+label+'</button>';}
 function countFilled(){const p=current().profile;return [p.basics.name,p.basics.label,p.basics.phone||p.basics.email,p.basics.summary,p.education.length,p.work.length||p.projects.length,p.skills.length].filter(Boolean).length;}
 function updateCompletion(){const el=$('#completion');if(el)el.innerHTML=completion();}
 function completion(){const n=countFilled();return '<div class="progress-row">'+Array.from({length:7},(_,i)=>'<i class="'+(i<n?'done':'')+'"></i>').join('')+'</div><span class="completion">已填写 '+n+' 项常用信息 · 其他栏目按需填写</span>';}
 function field(path,label,placeholder='',type='text',full=false,array=false){const v=path.split('.').reduce((a,k)=>a&&a[k],current().profile)??'';const value=Array.isArray(v)?v.join('、'):v;return '<label class="field '+(full?'full':'')+'"><span class="field-label">'+esc(label)+'</span>'+(type==='area'?'<textarea data-field="'+esc(path)+'" '+(array?'data-array="true"':'')+' placeholder="'+esc(placeholder)+'">'+esc(value)+'</textarea>':'<input type="'+type+'" data-field="'+esc(path)+'" value="'+esc(value)+'" placeholder="'+esc(placeholder)+'" '+(type==='email'?'inputmode="email"':type==='tel'?'inputmode="tel"':'')+'>')+'</label>';}
 function basicForm(){const b=current().profile.basics;return '<div class="card"><div class="photo-area">'+button(b.image?'<img alt="简历照片" src="'+esc(b.image)+'">':icon('photo',24)+'<span>添加照片</span>','photo','avatar')+'<div class="photo-info"><h3>简历照片 <span class="muted small-text">选填</span></h3><p>选择照片后可调整裁剪。<br>不含照片的模板也可正常使用。</p><div class="row">'+button(b.image?'更换／裁剪':'选择照片','photo','btn secondary small')+(b.image?button('移除','remove-photo','btn ghost small'):'')+'</div></div></div><div class="form-grid">'+field('basics.name','姓名','你的姓名')+field('basics.label','求职意向','例如：产品运营')+field('basics.phone','手机','联系电话','tel')+field('basics.email','邮箱','接收面试通知的邮箱','email')+field('basics.location.city','所在城市','例如：上海')+field('basics.birthDate','出生年月','选填，例如：2002.08')+field('basics.url','个人网站／作品集','选填','url',true)+field('basics.location.address','地址','选填','text',true)+field('basics.summary','个人简介','简要说明你的经验、优势和求职方向','area',true)+'</div><p class="hint">不填写的栏目会自动隐藏。手机号、出生年月、地址和照片都按需提供。</p></div><div id="completion">'+completion()+'</div>'+button('下一步：挑选模板 '+icon('chevron',16),'nav-gallery','btn full continue');}
 function entryForm(){const list=current().profile[module]||[];return list.map((e,i)=>'<div class="entry-card"><div class="entry-head"><strong>'+esc(e.name||e.institution||e.title||e.language||(sectionNames[module]+' '+(i+1)))+'</strong><div class="entry-actions">'+button(icon('up',17),'entry-up','icon-btn','data-index="'+i+'" aria-label="上移" '+(i===0?'disabled':''))+button(icon('down',17),'entry-down','icon-btn','data-index="'+i+'" aria-label="下移" '+(i===list.length-1?'disabled':''))+button(icon('trash',17),'entry-remove','icon-btn','data-index="'+i+'" aria-label="移除此条"')+'</div></div><div class="form-grid">'+forms[module].map(([key,label,place,type,arr])=>field(module+'.'+i+'.'+key,label,place,type||'text',type==='area',arr==='array')).join('')+(module==='work'||module==='projects'?field(module+'.'+i+'.highlights','亮点／成果清单','每行一条，模板会排成列表','area',true,true):'')+'</div></div>').join('')+(list.length?'':'<div class="card empty">'+icon(module==='work'?'briefcase':'document',33)+'<h3>添加'+esc(sectionNames[module])+'</h3><p>没有这类经历可以跳过，简历中不会显示空栏目。</p></div>')+button(icon('plus',17)+' 添加'+esc(sectionNames[module]),'entry-add','add-entry')+button('查看套用效果 '+icon('chevron',16),'nav-preview','btn secondary full');}
 function editor(){return '<div class="page"><div class="page-title"><div><h1>填写资料</h1><p>填写一次，切换模板自动套入。</p></div>'+button(icon('upload',16)+' 导入','import','btn secondary small')+'</div>'+(!state.welcomeSeen?'<div class="card welcome"><div class="welcome-art"><i></i><i></i><i></i><i></i><i></i></div><div><h2>先看样式，再填资料</h2><p>不用填写，也能查看完整模板。<br>选好后填写或导入，资料会自动套入。</p><div class="row">'+button('先看模板','nav-gallery','btn small')+button('开始填写','dismiss-welcome','btn ghost small')+'</div></div></div>':'')+'<div class="module-tabs">'+sections.map(([key,name])=>button(esc(name)+(key!=='basics'&&current().profile[key].length?'<span class="count">'+current().profile[key].length+'</span>':''),'module','tab '+(module===key?'active':''),'data-module="'+key+'"')).join('')+'</div>'+(module==='basics'?basicForm():entryForm())+'</div>';}
 function filteredTemplates(){return getEngine().templates.filter(t=>(category==='全部'||category==='收藏'&&state.favorites.includes(t.id)||t.category===category)&&(!query||[t.name,t.id,t.familyName,t.paletteName,...(t.tags||[])].join(' ').toLowerCase().includes(query.toLowerCase()))).sort((a,b)=>((parseInt(a.id.slice(1))-1)%25)-((parseInt(b.id.slice(1))-1)%25)||a.id.localeCompare(b.id));}
 const svgCache=new Map();function thumb(id){if(!svgCache.has(id))svgCache.set(id,'data:image/svg+xml;charset=utf-8,'+encodeURIComponent(getEngine().thumbnail(id)));return svgCache.get(id);}
 function templateCards(){const list=filteredTemplates();return list.slice(0,visibleCount).map(t=>'<div class="template-card '+(current().templateId===t.id?'selected':'')+'">'+(current().templateId===t.id?'<span class="selected-badge">当前模板</span>':'')+button(icon('star',15),'favorite','favorite '+(state.favorites.includes(t.id)?'on':''),'data-id="'+t.id+'" aria-label="'+(state.favorites.includes(t.id)?'取消收藏':'收藏模板')+'"')+button('<div class="template-paper"><img loading="lazy" alt="'+esc(t.name)+'布局预览" src="'+thumb(t.id)+'"></div><div class="template-name">'+esc(t.name)+'</div><div class="template-sub">'+esc(t.category)+' · '+esc(t.paletteName||t.familyName)+'</div>','template-open','template-open','data-id="'+t.id+'"')+'</div>').join('')||'<div class="empty" style="grid-column:1/-1"><h3>'+(category==='收藏'?'还没有收藏的模板':'没有找到匹配的模板')+'</h3><p>试试其他分类，或缩短搜索词。</p></div>';}
 function gallery(){const cats=['全部','收藏',...new Set(getEngine().templates.map(t=>t.category))],total=filteredTemplates().length;return '<div class="page"><div class="page-title"><div><h1>挑选模板</h1><p>'+getEngine().templates.length+' 款样式 · '+(hasProfileData()?'自动套入你的资料':'不用填写也能看完整示例')+'</p></div></div><div class="search">'+icon('search',18)+'<input id="template-search" placeholder="搜索风格、模板名或编号" value="'+esc(query)+'" aria-label="搜索模板"></div><div class="filters">'+cats.map(c=>button((c==='收藏'?icon('star',13):'')+esc(c),'category','chip '+(category===c?'active':''),'data-category="'+esc(c)+'"')).join('')+'</div><div class="gallery-meta"><span id="template-count">'+total+' 款'+(query?'匹配样式':'可选样式')+'</span>'+button('模板库说明','template-info','')+'</div><div class="template-grid" id="template-grid">'+templateCards()+'</div><div class="gallery-more" id="gallery-more">'+(total>visibleCount?button('再看 24 款 '+icon('down',16),'more-templates','btn ghost'):'')+'</div></div>';}
 function updateGallery(){const grid=$('#template-grid');if(grid)grid.innerHTML=templateCards();const total=filteredTemplates().length;if($('#template-count'))$('#template-count').textContent=total+' 款可选样式';if($('#gallery-more'))$('#gallery-more').innerHTML=total>visibleCount?button('再看 24 款 '+icon('down',16),'more-templates','btn ghost'):'';}
 function iframeMarkup(html,id='resume-frame',zoom=false,templateId=current().templateId,source='mine',context='preview'){
  return (!zoom?'<div class="preview-tools">'+button(icon('search',14)+' 放大查看','zoom-preview','btn ghost small')+'</div>':'')+'<div class="preview-viewport"><iframe title="简历完整预览" sandbox="allow-same-origin" class="resume-frame" '+(zoom?'data-zoom="true"':'data-fit-template="'+esc(templateId)+'" data-preview-source="'+source+'" data-preview-context="'+context+'"')+' id="'+id+'" srcdoc="'+esc(html)+'"></iframe></div>'+(!zoom?'<p class="fit-note" data-fit-note>正在按目标页数整理排版…</p>':'');
 }
 const documentCache=new Map();
 function prepareDocument(templateId,record=current()){
  const profile=clone(record.profile),settings=clone(record.settings),key=record.id+'|'+record.updatedAt+'|'+templateId+'|'+JSON.stringify(settings);
  if(documentCache.has(key))return documentCache.get(key);
  const promise=getEngine().fitHtml?getEngine().fitHtml(profile,templateId,settings):Promise.resolve({html:getEngine().html(profile,templateId,settings),effective:settings,estimatedPages:1,adjusted:false,fitsEstimate:true});
  documentCache.set(key,promise);if(documentCache.size>8)documentCache.delete(documentCache.keys().next().value);
  promise.catch(()=>documentCache.delete(key));return promise;
 }
 function pageControls(){const s=current().settings;return '<div class="card page-controls"><label class="field"><span class="field-label">简历页数</span><select data-setting="pageTarget"><option value="1" '+(s.pageTarget===1?'selected':'')+'>一页（默认）</option><option value="2" '+(s.pageTarget===2?'selected':'')+'>两页</option></select></label><label class="check-label small-text"><input type="checkbox" data-setting="autoFit" '+(s.autoFit?'checked':'')+'>自动调整留白、行距和字号</label><p class="hint">优先做成一页。内容放不下时会提示调整，资料不会被截掉。</p></div>';}
 function tuneControls(){const r=current(),s=r.settings;return '<details class="card tune"><summary>排版调整 '+icon('settings',18)+'</summary><div class="tune-grid"><label class="field"><span class="field-label">正文字号</span><select data-setting="fontSize">'+[10,11,12,13,14,15,16].map(v=>'<option value="'+v+'" '+(s.fontSize===v?'selected':'')+'>'+v+' px</option>').join('')+'</select></label><label class="field"><span class="field-label">行间距</span><select data-setting="lineHeight">'+[1.35,1.45,1.55,1.7,1.85].map(v=>'<option value="'+v+'" '+(s.lineHeight===v?'selected':'')+'>'+v+'</option>').join('')+'</select></label><label class="field"><span class="field-label">页边留白</span><select data-setting="margin">'+[22,28,32,40,48].map(v=>'<option value="'+v+'" '+(s.margin===v?'selected':'')+'>'+v+' px</option>').join('')+'</select></label><label class="field"><span class="field-label">照片样式</span><select data-setting="photoShape"><option value="square" '+(s.photoShape==='square'?'selected':'')+'>证件照</option><option value="circle" '+(s.photoShape==='circle'?'selected':'')+'>圆形</option></select></label><label class="check-label small-text"><input type="checkbox" data-setting="photoEnabled" '+(s.photoEnabled?'checked':'')+'>展示照片</label>'+button('恢复模板默认','reset-settings','btn ghost small')+'<div class="field full"><span class="field-label">主题颜色</span><div class="color-row">'+['#245bdd','#263c59','#347869','#994f47','#6a579b','#237f94','#8b713e','#222222'].map(c=>button('','accent','color-dot '+(s.accentOverride===c?'active':''),'data-color="'+c+'" style="--color:'+c+'" aria-label="主题色 '+c+'"')).join('')+'</div></div></div><div class="order-list"><span class="field-label">栏目顺序与显示</span>'+s.sectionOrder.map((k,i)=>'<div class="order-item"><label class="check-label"><input type="checkbox" data-section-visible="'+k+'" '+(!s.hiddenSections.includes(k)?'checked':'')+'>'+sectionNames[k]+'</label><div class="row">'+button(icon('up',15),'section-up','icon-btn','data-index="'+i+'" aria-label="上移 '+sectionNames[k]+'" '+(i===0?'disabled':''))+button(icon('down',15),'section-down','icon-btn','data-index="'+i+'" aria-label="下移 '+sectionNames[k]+'" '+(i===s.sectionOrder.length-1?'disabled':''))+'</div></div>').join('')+'</div></details>';}
 function preview(){
  const actual=current(),t=getEngine().templates.find(t=>t.id===actual.templateId),source=previewSource(),r=previewRecord(source);
  return '<div class="page"><div class="page-title"><div><h1>预览与导出</h1><p>先看样式，填写后导出自己的简历。</p></div></div><div class="preview-toolbar"><strong>'+esc(t.name)+'</strong>'+button('换个模板','nav-gallery','btn ghost small')+'</div>'+previewPicker(source)+previewNotice(source)+pageControls()
   +'<div class="preview-wrap">'+iframeMarkup(getEngine().html(r.profile,actual.templateId,r.settings),'resume-frame',false,actual.templateId,source)+'<div class="preview-caption">A4 排版 · '+(source==='sample'?'虚构示例':hasProfileData()?'你的实际资料':'空资料')+' · 可向下滚动查看全文</div></div>'
   +(!hasProfileData()?'<div class="preview-start">'+button(icon('edit',17)+' 填写我的资料','nav-editor','btn full')+button(icon('upload',17)+' 导入已有简历','import','btn secondary full')+'</div>':'')
   +'<div class="export-actions">'+button(icon('download',19)+' 保存为 PDF','pdf-save','btn primary-export')+button(icon('edit',17)+' 返回修改资料','nav-editor','btn ghost')+button(icon('share',17)+' 分享文件','pdf-share','btn secondary')+'</div><div class="share-options">'+button('<span class="wechat">'+icon('message',23)+'</span>微信','pdf-wechat','share-btn')+button('<span class="qq">'+icon('message',23)+'</span>QQ','pdf-qq','share-btn')+button(icon('share',23)+'更多应用','pdf-share','share-btn')+'</div>'+tuneControls()
   +'<details class="card tune"><summary>导出前检查 '+icon('check',17)+'</summary><ul class="checklist">'+[[actual.profile.basics.name,'已填写姓名'],[actual.profile.basics.phone||actual.profile.basics.email,'已留联系方式'],[actual.profile.work.length||actual.profile.education.length||actual.profile.projects.length,'已添加相关经历']].map(([v,label])=>'<li>'+icon(v?'check':'info',15)+label+(v?'':'（建议补充）')+'</li>').join('')+'</ul><p class="hint">分享会打开所选应用，收件人由你选择。发送文件需要 QQ／微信自身的网络连接。</p></details></div>';
 }
 function mine(){return '<div class="page"><div class="page-title"><div><h1>我的简历</h1><p>为不同岗位保存不同版本。</p></div>'+button(icon('plus',17)+' 新建','new','btn small')+'</div><div class="resume-list">'+state.resumes.map(r=>'<div class="resume-item '+(r.id===state.currentId?'active':'')+'">'+button(icon('document',24),'switch','mini-doc','data-id="'+r.id+'" aria-label="打开 '+esc(r.title)+'"')+'<div class="resume-item-info">'+button('<span>'+esc(r.title)+'</span>','switch','doc-selector','data-id="'+r.id+'"')+'<p>'+esc(r.profile.basics.label||'未设置求职意向')+' · '+new Date(r.updatedAt).toLocaleDateString('zh-CN')+'</p></div>'+button(icon('more',20),'record-menu','icon-btn','data-id="'+r.id+'" aria-label="管理 '+esc(r.title)+'"')+'</div>').join('')+'</div><div class="card menu-card">'+menuRow('upload','导入资料／恢复备份','import')+menuRow('download','备份全部简历','backup')+menuRow('document','导出当前资料 JSON','export-json')+'</div><div class="card menu-card">'+menuRow('message','反馈与问题记录','feedback')+menuRow('shield','隐私与数据保存','privacy')+menuRow('info','使用帮助与开源许可','help')+'</div><div class="about-foot">简历工坊 1.0.1 · 全部模板内置<br>资料与照片保存在本机 · 无账号</div></div>';}
 function menuRow(ic,label,action){return button('<span class="row">'+icon(ic,19)+esc(label)+'</span>'+icon('chevron',16),action,'menu-row');}
 function render(){const r=current();$('#app').innerHTML='<div class="shell"><header class="topbar"><div class="brand"><span class="brand-mark">'+icon('document',22)+'</span><strong>简历工坊</strong></div>'+button(icon('info',21),'help','icon-btn','aria-label="使用帮助"')+'</header><div class="document-bar">'+button('<span>'+esc(r.title)+'</span>'+icon('down',14),'documents','doc-selector')+'<span class="saved" id="save-status"></span></div>'+({editor,gallery,preview,mine}[screen]||editor)()+'</div><nav class="bottom-nav" aria-label="主导航">'+[['editor','edit','资料'],['gallery','grid','模板'],['preview','eye','预览'],['mine','folder','我的']].map(([s,ic,label])=>button(icon(ic,21)+label,'nav-'+s,screen===s?'active':'','aria-label="'+label+'" '+(screen===s?'aria-current="page"':''))).join('')+'</nav>';savedStatus();bindFrames();}
 function nav(s){save();screen=s;if(s==='preview')previewMode='auto';closeModal();render();window.scrollTo(0,0);}
 function openModal(title,body,footer=''){modalActive=true;$('#modal-root').innerHTML='<div class="modal-backdrop"><section class="modal" role="dialog" aria-modal="true" aria-label="'+esc(title)+'"><div class="modal-header"><h2>'+esc(title)+'</h2>'+button(icon('close',22),'close-modal','icon-btn','aria-label="关闭"')+'</div><div class="modal-content">'+body+'</div>'+(footer?'<div class="modal-footer">'+footer+'</div>':'')+'</section></div>';bindFrames();}
 function closeModal(){modalActive=false;$('#modal-root').innerHTML='';}
 function bindFrames(){document.querySelectorAll('.resume-frame').forEach(f=>{
  const resize=()=>{try{const d=f.contentDocument;if(!d||!d.body)return;const height=Math.max(1123,d.documentElement.scrollHeight,d.body.scrollHeight);const viewport=f.parentElement;const scale=f.dataset.zoom==='true'?1:viewport.clientWidth/794;f.style.height=height+'px';f.style.transform='scale('+scale+')';viewport.style.height=Math.ceil(height*scale)+'px';}catch(_){}};
  f.onload=()=>{resize();setTimeout(resize,90);setTimeout(resize,600);};setTimeout(resize,100);
  if(f.dataset.fitTemplate){const request=uid();f.dataset.fitRequest=request;const source=f.dataset.previewSource||'mine',record=previewRecord(source,f.dataset.previewContext||'preview'),target=record.settings.pageTarget;
   prepareDocument(f.dataset.fitTemplate,record).then(result=>{if(!f.isConnected||f.dataset.fitRequest!==request)return;if(f.srcdoc!==result.html)f.srcdoc=result.html;const note=f.closest('.preview-wrap')?.querySelector('[data-fit-note]');if(note){note.textContent=source==='sample'?'示例排版 · '+(result.estimatedPages===1?'一页效果':'全文可向下滚动查看')+(result.adjusted?' · 已自动调整排版':''):!result.fitsEstimate?'资料较多，估计需要 '+result.estimatedPages+' 页；'+(target===1?'可精简内容或选择两页。':'请精简内容后再导出。'):(target===1?'一页目标':'两页目标')+(result.adjusted?' · 已自动调整排版':' · 当前排版已适配')+'。网页页数为估计，实际PDF导出需APK。';note.classList.toggle('fit-overflow',!result.fitsEstimate);}}).catch(()=>{const note=f.closest('.preview-wrap')?.querySelector('[data-fit-note]');if(note)note.textContent='自动适配暂时未完成，可调整排版后重试。';});
  }
 });}
 function refreshPreview(){const f=$('#resume-frame');if(f){const source=previewSource(),r=previewRecord(source);f.dataset.previewSource=source;f.srcdoc=getEngine().html(r.profile,current().templateId,r.settings);bindFrames();}}
 function busy(message){const existing=$('.busy-overlay');if(existing){existing.querySelector('p').textContent=message;return;}const e=document.createElement('div');e.className='busy-overlay';e.innerHTML='<div class="busy-box"><div class="spinner"></div><p></p></div>';e.querySelector('p').textContent=message;document.body.appendChild(e);clearTimeout(busyTimer);busyTimer=setTimeout(()=>{unbusy();toast('操作还未完成，可重试；原资料已保留。',4500);},45000);}
 function unbusy(){clearTimeout(busyTimer);$('.busy-overlay')?.remove();}
 function filename(ext){const b=current().profile.basics;return (b.name||current().title||'简历').replace(/[\\/:*?"<>|\u0000-\u001f]/g,'_').slice(0,60)+'_简历.'+ext;}
 function saveText(content,name,type='application/json'){save();if(window.Native){busy('正在打开保存位置…');try{Native.saveText(content,name,type);}catch(_){unbusy();toast('无法打开保存位置，请重试。');}}else{const blob=new Blob([content],{type});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),4000);toast('已生成下载文件');}}
 function standardJson(profile){const p=clone(profile);const iso=v=>{const s=String(v||'').trim();if(/^(至今|现在|present|current)$/i.test(s)||!s)return null;return s.replace(/年|[./]/g,'-').replace(/月$/,'').replace(/日$/,'').replace(/-(\d)(?=-|$)/g,'-0$1');};for(const k of ['work','education','projects','awards','certificates'])for(const item of p[k]||[])for(const key of ['startDate','endDate','date'])if(key in item){const d=iso(item[key]);if(d)item[key]=d;else delete item[key];}function clean(o){if(Array.isArray(o))return o.map(clean);if(o&&typeof o==='object'){const out={};for(const [k,v] of Object.entries(o))if(v!==''&&v!==null&&v!==undefined)out[k]=clean(v);return out;}return o;}return clean(p);}
 function emptyExport(){openModal('先填写你的资料','<p>示例内容只用于查看模板。请填写或导入自己的资料后，再保存或分享简历。</p>',button('继续看模板','close-modal','btn ghost')+button('去填写','nav-editor','btn'));}
 function demoPdf(){openModal('网页演示中的保存与分享','<p>这里可以操作资料、模板、照片和排版预览；Android的文件保存、真实PDF页数检查及QQ／微信分享需要安装APK。</p><p>网页演示不会替你发送文件，也不会把示例导出为个人资料。</p><a class="btn full" href="/resume-studio/releases/ResumeStudio-1.0.1.apk" download>下载 Android APK</a>',button('返回演示','close-modal','btn ghost'));}
 function exportPdf(mode){
  if(!hasProfileData()){emptyExport();return;}
  if(window.RESUME_WEB_DEMO){demoPdf();return;}
  if(previewSource()==='sample'){previewMode='mine';render();openModal('导出你的简历','<p>已切换为你的真实资料。保存或分享将使用你填写的内容，请确认当前排版。</p>',button('先核对资料','close-modal','btn ghost')+button('导出我的简历','pdf-confirm','btn','data-mode="'+mode+'"'));return;}
  if(!current().profile.basics.name){openModal('还没有填写姓名','<p>建议先填写姓名和联系方式，再导出简历。</p>',button('继续导出','pdf-confirm','btn ghost','data-mode="'+mode+'"')+button('去填写','nav-editor','btn'));return;}
  doPdf(mode);
 }
 async function doPdf(mode){if(window.RESUME_WEB_DEMO){demoPdf();return;}if($('.busy-overlay'))return;if(!hasProfileData()){emptyExport();return;}save();closeModal();const r=current(),w=!window.Native?window.open('','_blank'):null;busy('正在按'+(r.settings.pageTarget===1?'一页':'两页')+'目标生成 PDF…');try{const result=await prepareDocument(r.templateId,r);if(window.Native)Native.exportPdf(result.html,filename('pdf'),mode,r.settings.pageTarget);else{unbusy();if(w){w.document.write(result.html);w.document.close();setTimeout(()=>w.print(),450);}else toast('请在安装后的 Android 应用中导出 PDF。');}}catch(_){unbusy();toast('PDF 生成失败，可重试。');}}
 window.onNativeResult=result=>{unbusy();if(typeof result==='string'){try{result=JSON.parse(result);}catch(_){result={ok:false,message:'操作返回异常，请重试。'};}}
  if(result?.type==='pdf'&&!result.ok&&result.pages>(result.pageLimit||current().settings.pageTarget)){const limit=result.pageLimit||current().settings.pageTarget;openModal((limit===1?'一页':'两页')+'暂时放不下','<p>当前完整排版需要 <strong>'+result.pages+' 页</strong>。'+(current().settings.autoFit?'已经在可读范围内调整了留白、行距和字号。':'可以开启自动适配，或手动调整排版。')+'</p><p>资料完整保留。请精简内容'+(limit===1?'，也可以改为两页':'')+'后再导出。</p>',button('返回修改资料','nav-editor','btn ghost')+(limit===1?button('改为两页并预览','page-two','btn'):button('返回预览','close-modal','btn')));return;}
  toast(result?.message||(result?.ok?'操作已完成':'操作未完成，可重试。'),result?.ok?2800:5000);
 };
 window.onNativePause=()=>save();
 window.onNativeBack=()=>{if($('.busy-overlay'))return true;if(modalActive){closeModal();return true;}if(screen!=='editor'){nav('editor');return true;}return false;};
 function importMenu(){openModal('导入资料','<p>导入到一份新简历，原来的简历会保留。</p>'+button(icon('document',23)+'<span><strong>选择文件</strong><small>Word DOCX、文字版 PDF、TXT、JSON 或备份</small></span>'+icon('chevron',18),'import-file','import-choice')+button(icon('edit',23)+'<span><strong>粘贴文字</strong><small>从旧简历复制，离线整理成可编辑资料</small></span>'+icon('chevron',18),'import-paste','import-choice')+'<p class="hint">扫描图片 PDF 暂无 OCR。旧版 DOC 请先另存为 DOCX。</p>');}
 function reviewImport(result,name){pendingImport=result;const p=result.profile;if(result.kind==='backup'){openModal('恢复备份','<p>将新增 '+result.records.length+' 份简历，当前资料会保留。</p><div class="import-review">'+result.records.map(r=>esc(r.title)).join('\n')+'</div>',button('取消','close-modal','btn ghost')+button('导入备份','import-apply','btn'));return;}
   const populated=[['姓名',p.basics.name],['意向',p.basics.label],['手机',p.basics.phone],['邮箱',p.basics.email],['城市',p.basics.location.city]].filter(([,v])=>v).map(([k,v])=>k+'：'+v).join('\n');
   const stats=Object.keys(sectionNames).filter(k=>Array.isArray(p[k])&&p[k].length).map(k=>sectionNames[k]+' '+p[k].length+' 项').join(' · ');
   result.title=(p.basics.name||name||'导入')+'的简历';
   openModal('确认导入内容','<p>'+(result.warnings?.length?esc(result.warnings.join(' ')):'已读取结构化资料，可以继续编辑。')+'</p><div class="import-review">'+esc(populated||'未自动提取到基本信息，可在导入后手动填写。')+'\n\n'+esc(stats)+'</div>'+((p.custom||[]).some(x=>x.title==='导入待整理')?'<p class="notice">其余文字已放入“自定义 → 导入待整理”，请检查后整理到相应栏目。</p>':'')+'<details><summary class="small-text muted">查看原始文字</summary><div class="import-review">'+esc(result.text||'JSON资料')+'</div></details>',button('取消','close-modal','btn ghost')+button('导入并校对','import-apply','btn'));
 }
 async function importFile(file){closeModal();busy('正在离线读取文件…');try{const result=await ResumeImport.readFile(file,msg=>busy(msg));unbusy();reviewImport(result,file.name.replace(/\.[^.]+$/,''));}catch(e){unbusy();openModal('暂时无法导入','<p>'+esc(e.message||'文件读取失败，请换一个文件。')+'</p>',button('重新选择','import-file','btn ghost')+button('粘贴文字','import-paste','btn'));}}
 function applyImport(){const result=pendingImport;if(!result)return;const records=result.kind==='backup'?result.records:[{profile:result.profile,title:result.title}];if(state.resumes.length+records.length>50){toast('最多保存 50 份简历，请先整理现有资料。');return;}const old=clone(state);const added=records.map(r=>{const rec=newRecord(r.profile,r.title);if(getEngine().templates.some(t=>t.id===r.templateId))rec.templateId=r.templateId;rec.settings=sanitizeSettings(r.settings);return rec;});state.resumes.push(...added);state.currentId=added[0].id;state.welcomeSeen=true;if(result.kind==='backup')state.favorites=[...new Set([...state.favorites,...result.favorites.filter(x=>getEngine().templates.some(t=>t.id===x))])];if(!save()){state=old;return;}pendingImport=null;module='basics';nav('editor');toast('已导入，检查资料后再挑选模板。');}
 async function choosePhoto(file){if(!file)return;if(file.size>20*1024*1024){toast('请选用 20 MB 以内的照片。');return;}busy('正在读取照片…');try{const url=URL.createObjectURL(file),img=new Image();await new Promise((res,rej)=>{img.onload=res;img.onerror=rej;img.src=url;});URL.revokeObjectURL(url);const ratio=Math.min(1,1400/Math.max(img.width,img.height));const canvas=document.createElement('canvas');canvas.width=Math.round(img.width*ratio);canvas.height=Math.round(img.height*ratio);canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);photoSource=new Image();await new Promise(res=>{photoSource.onload=res;photoSource.src=canvas.toDataURL('image/jpeg',.9);});unbusy();openPhotoEditor();}catch(_){unbusy();toast('照片格式无法读取，请换用 JPG、PNG 或 WebP。',4500);}}
 function openPhotoEditor(){openModal('调整简历照片','<div class="photo-editor"><div class="crop-view"><img id="crop-photo" alt="照片裁剪预览" src="'+photoSource.src+'"></div><label class="field"><span class="field-label">放大</span><input id="crop-zoom" type="range" min="1" max="3" step="0.05" value="1"></label><label class="field"><span class="field-label">上下位置</span><input id="crop-y" type="range" min="0" max="100" step="1" value="50"></label><label class="field"><span class="field-label">左右位置</span><input id="crop-x" type="range" min="0" max="100" step="1" value="50"></label><p class="hint">本机裁剪并压缩照片，原相册文件不会改动。</p></div>',button('更换照片','photo-replace','btn ghost')+button('取消','close-modal','btn ghost')+button('使用照片','photo-apply','btn'));}
 function cropPhoto(){if(!photoSource)return;const img=photoSource,z=+$('#crop-zoom').value,x=+$('#crop-x').value/100,y=+$('#crop-y').value/100,targetW=360,targetH=480;const ratio=Math.max(targetW/img.width,targetH/img.height)*z;const sw=targetW/ratio,sh=targetH/ratio,sx=(img.width-sw)*x,sy=(img.height-sh)*y;const canvas=document.createElement('canvas');canvas.width=targetW;canvas.height=targetH;const ctx=canvas.getContext('2d');ctx.fillStyle='#ffffff';ctx.fillRect(0,0,targetW,targetH);ctx.drawImage(img,sx,sy,sw,sh,0,0,targetW,targetH);current().profile.basics.image=canvas.toDataURL('image/jpeg',.86);photoSource=null;changed();save();closeModal();render();toast('照片已添加并保存');}
 function documents(){openModal('选择简历',state.resumes.map(r=>menuRow('document',r.title,'switch').replace('data-action="switch"','data-action="switch" data-id="'+r.id+'"')).join('')+menuRow('plus','新建简历','new'));}
 function recordMenu(id){const r=state.resumes.find(r=>r.id===id);if(!r)return;openModal(r.title,['rename','duplicate','delete'].map((a,i)=>button('<span class="row">'+icon(['edit','copy','trash'][i],19)+['重命名','复制成新简历','删除这份简历'][i]+'</span>'+icon('chevron',16),a,'menu-row','data-id="'+id+'"')).join(''));}
 function help(){openModal('使用帮助','<p class="hint">简历工坊1.0.1网页演示：真实应用界面和操作。资料只存当前浏览器，不自动同步至APK。</p><h3>三步完成简历</h3><p>① 可先看模板示例，再填写或导入资料，按需添加照片和经历。<br>② 在模板页选样式，所有模板自动套入同一份资料。<br>③ 在预览页查看全文，再保存 PDF 或分享到 QQ／微信。</p><h3>未填资料也能预览</h3><p>模板详情与预览页都可切换“示例效果／我的资料”。空资料默认显示完整虚构示例；示例只展示，不会填入资料或进入备份。选择模板后填写或导入，自动套入自己的内容。导出始终使用自己的资料。</p><h3>一页与两页</h3><p>默认一页，可在预览页改为两页。自动适配会有限度地调整留白、行距和字号；自动缩小的字号最低为 11 px。网页仅提供排版预览和估计页数。APK导出时检查真实PDF页数，超限保护保留完整资料。</p><h3>导入与备份</h3><p>支持 JSON Resume、应用备份、TXT、DOCX 和文字版 PDF。非结构化文字通过本机规则提取，需要校对；未匹配文字会保留在自定义栏目。扫描 PDF 和图片文字暂不识别。<br>“我的”可备份全部简历；恢复时新增记录，保留已有简历。</p><h3>模板数量</h3><p>40 个基础设计族 × 25 组配色与版式预设，共 1,000 款可选样式。字体、行距、页边距和栏目顺序可进一步调整。</p><h3>网页与APK的能力边界</h3><p>网页演示不能直接保存Android PDF或唤起QQ／微信分享；这些功能需要APK。网页数据不与APK自动同步，可自行下载JSON备份再导入。<br>导出为真实 PDF 文件；系统分享面板中选择 QQ／微信，再由你指定联系人。应用本身不需要联网，聊天应用发送时需要自己的网络。<br>当前没有在线更新源。之后安装同包、同签名新版 APK 可保留本机资料，建议更新前导出备份。</p>'+menuRow('document','开源组件与许可','licenses')+menuRow('shield','隐私说明','privacy'));}
 function privacy(){openModal('隐私与数据保存','<button class="btn secondary" data-action="demo-reset">重置网页演示资料</button><p>姓名、联系方式、经历与照片仅保存在当前浏览器的本机存储；不注册账号，不上传资料，无广告与追踪。</p><p>选择照片或文件只授予本次选择的访问。分享时仅将你当前生成的 PDF 交给所选应用；收件人和发送由你完成。</p><p>清除浏览器网站数据或重置演示会移除本机演示资料。请通过“我的 → 备份全部简历”保存备份。备份含个人资料和照片，请保存在你信任的位置。</p><p>问题反馈只保存你主动填写的文字，本机诊断默认不包含简历正文、照片与联系方式。没有远程收件端，反馈未自动发送给开发者。</p><label class="check-label small-text"><input id="diagnostics-toggle" type="checkbox" '+(state.diagnosticsEnabled?'checked':'')+'>记录本机技术错误（可关闭）</label>');}
 function licenses(){openModal('开源组件与许可','<p>简历模板主体适配 Reactive Resume 的 Onyx／Azurill 布局，MIT 许可；资料字段兼容 JSON Resume schema。</p><p>PDF.js：Apache-2.0，用于离线提取 PDF 文字。<br>fflate：MIT，用于读取 DOCX 正文。<br>全部第三方许可随安装包与源码附带。模板与导出使用 Android 系统字体，未捆绑来源不明的字体。</p>'+menuRow('document','Reactive Resume MIT 许可','license-read').replace('data-action="license-read"','data-action="license-read" data-file="reactive-resume.txt"')+menuRow('document','JSON Resume MIT 许可','license-read').replace('data-action="license-read"','data-action="license-read" data-file="json-resume.txt"')+menuRow('document','PDF.js Apache 许可','license-read').replace('data-action="license-read"','data-action="license-read" data-file="pdfjs.txt"')+menuRow('document','fflate MIT 许可','license-read').replace('data-action="license-read"','data-action="license-read" data-file="fflate.txt"'));}
 function feedback(){openModal('反馈与问题记录','<p>记录使用问题或建议，保存在本机。需要交给开发者时可导出；当前没有配置远程收件端。</p><label class="field"><span class="field-label">反馈内容</span><textarea id="feedback-input" maxlength="3000" placeholder="例如：使用哪款模板、进行了什么操作、希望怎样改进。请勿填写姓名、电话等个人资料。"></textarea></label>'+(state.feedback.length?'<p class="hint">已保存 '+state.feedback.length+' 条本机反馈。</p>'+button('导出本机反馈','feedback-export','btn ghost full'):'') ,button('取消','close-modal','btn ghost')+button('保存到本机','feedback-save','btn'));}
 const actions={
  'dismiss-welcome':()=>{state.welcomeSeen=true;save();render();},
  'module':el=>{module=el.dataset.module;save();render();},
  'new':()=>{if(state.resumes.length>=50){toast('最多保存 50 份简历');return;}const r=newRecord(null,'我的简历 '+(state.resumes.length+1));state.resumes.push(r);state.currentId=r.id;state.welcomeSeen=true;save();module='basics';nav('editor');},
  'sample':()=>{const r=newRecord(clone(getEngine().sampleProfile),'示例简历');state.resumes.push(r);state.currentId=r.id;state.welcomeSeen=true;save();module='basics';nav('editor');toast('示例资料已加载，可以修改后体验模板。');},
  'documents':documents,'switch':el=>{save();state.currentId=el.dataset.id;module='basics';nav('editor');},'record-menu':el=>recordMenu(el.dataset.id),
  'rename':el=>{const r=state.resumes.find(r=>r.id===el.dataset.id);openModal('重命名简历','<label class="field"><span class="field-label">简历名称</span><input id="rename-input" maxlength="80" value="'+esc(r.title)+'"></label>',button('取消','close-modal','btn ghost')+button('保存','rename-save','btn','data-id="'+r.id+'"'));},
  'rename-save':el=>{const value=$('#rename-input').value.trim();if(!value){toast('请输入简历名称');return;}state.resumes.find(r=>r.id===el.dataset.id).title=value;save();closeModal();render();},
  'duplicate':el=>{if(state.resumes.length>=50){toast('最多保存 50 份简历');return;}const r=clone(state.resumes.find(r=>r.id===el.dataset.id));r.id=uid();r.title+=' · 副本';r.updatedAt=Date.now();state.resumes.push(r);state.currentId=r.id;save();closeModal();render();toast('已复制，原简历仍保留');},
  'delete':el=>{const r=state.resumes.find(r=>r.id===el.dataset.id);openModal('删除这份简历','<p>将删除“'+esc(r.title)+'”的资料、照片和排版设置。其他简历不受影响。建议先导出备份。</p>',button('保留','close-modal','btn ghost')+button('确认删除','delete-confirm','btn danger','data-id="'+r.id+'"'));},
  'delete-confirm':el=>{state.resumes=state.resumes.filter(r=>r.id!==el.dataset.id);if(!state.resumes.length)state.resumes=[newRecord()];if(state.currentId===el.dataset.id)state.currentId=state.resumes[0].id;save();closeModal();render();toast('已删除所选简历');},
  'entry-add':()=>{const entry={};for(const [key,,,,array] of forms[module])entry[key]=array==='array'?[]:'';if(module==='work'||module==='projects')entry.highlights=[];current().profile[module].push(entry);changed();render();setTimeout(()=>document.querySelector('.entry-card:last-of-type')?.scrollIntoView({block:'start',behavior:'smooth'}),30);},
  'entry-remove':el=>{const i=+el.dataset.index;openModal('移除这条经历','<p>将移除当前'+esc(sectionNames[module])+'中的第 '+(i+1)+' 项。</p>',button('保留','close-modal','btn ghost')+button('确认移除','entry-remove-confirm','btn danger','data-index="'+i+'"'));},
  'entry-remove-confirm':el=>{current().profile[module].splice(+el.dataset.index,1);changed();closeModal();render();},
  'entry-up':el=>moveEntry(+el.dataset.index,-1),'entry-down':el=>moveEntry(+el.dataset.index,1),
  'category':el=>{category=el.dataset.category;visibleCount=24;render();},'more-templates':()=>{visibleCount+=24;updateGallery();},
  'favorite':el=>{const id=el.dataset.id;state.favorites=state.favorites.includes(id)?state.favorites.filter(x=>x!==id):[...state.favorites,id];save();updateGallery();},
  'template-info':()=>openModal('模板库说明','<p>内置 40 个基础设计族，每族提供 25 组配色与版式预设，共 1,000 款可选样式。不同设计族有单栏、双栏、侧栏、时间线等排版区别；同族样式共享结构。</p><p>模板缩略图用于辨认排版。空资料时打开模板会显示完整虚构示例，也能切换“我的资料”；姓名、照片、教育和工作经历按字段自动匹配，切换模板不会重新填资料。</p>'),
  'template-open':el=>openTemplate(el.dataset.id),
  'preview-source':el=>{if(el.dataset.previewContext==='template')openTemplate(el.dataset.id,el.dataset.source);else{previewMode=el.dataset.source;render();}},
  'template-use':el=>{current().templateId=el.dataset.id;current().settings.accentOverride=null;changed();nav('preview');toast(hasProfileData()?'已套入资料，换模板不影响填写内容':'模板已选好，填写或导入后会自动套入。');},
  'accent':el=>{current().settings.accentOverride=el.dataset.color;changed();refreshPreview();document.querySelectorAll('.color-dot').forEach(e=>e.classList.toggle('active',e.dataset.color===el.dataset.color));},
  'reset-settings':()=>{current().settings=clone(defaults);changed();render();},'section-up':el=>moveSection(+el.dataset.index,-1),'section-down':el=>moveSection(+el.dataset.index,1),
  'pdf-save':()=>exportPdf('save'),'pdf-share':()=>exportPdf('share'),'pdf-wechat':()=>exportPdf('wechat'),'pdf-qq':()=>exportPdf('qq'),'pdf-confirm':el=>doPdf(el.dataset.mode),
  'page-two':()=>{current().settings.pageTarget=2;changed();nav('preview');},
  'import':importMenu,'import-file':()=>$('#document-input').click(),'import-paste':()=>openModal('粘贴旧简历信息','<p>建议保留“教育经历”“工作经历”“技能”等栏目标题，以便整理。</p><textarea id="paste-input" style="min-height:240px" maxlength="180000" placeholder="姓名：张三\n求职意向：运营专员\n手机：13800138000\n邮箱：name@example.com\n教育经历\n2020.09 - 2024.06 学校名称 · 专业\n工作经历\n2024.07 - 至今 公司名称 · 岗位"></textarea>',button('取消','close-modal','btn ghost')+button('识别并校对','paste-parse','btn')),
  'paste-parse':()=>{try{reviewImport({kind:'profile',...ResumeImport.parseText($('#paste-input').value)},'导入');}catch(e){toast(e.message);}},'import-apply':applyImport,
  'photo':()=>{if(current().profile.basics.image){photoSource=new Image();photoSource.onload=openPhotoEditor;photoSource.src=current().profile.basics.image;}else $('#photo-input').click();},
  'photo-replace':()=>$('#photo-input').click(),'photo-apply':cropPhoto,'remove-photo':()=>{current().profile.basics.image='';changed();render();toast('已从这份简历移除照片');},
  'backup':()=>saveText(JSON.stringify({format:'resume-studio-backup',version:1,exportedAt:new Date().toISOString(),resumes:state.resumes,favorites:state.favorites},null,2),'简历工坊_全部备份_'+new Date().toISOString().slice(0,10)+'.json'),
  'export-json':()=>saveText(JSON.stringify(standardJson(current().profile),null,2),filename('json')),
  'zoom-preview':el=>{const html=el.closest('.preview-wrap')?.querySelector('.resume-frame')?.srcdoc||getEngine().html(current().profile,current().templateId,current().settings);openModal('放大查看','<p>左右滑动查看整页，向下滚动查看后续内容。</p><div class="preview-wrap zoom-preview">'+iframeMarkup(html,'zoom-frame',true)+'</div>',button('关闭放大','close-modal','btn'));},
  'feedback':feedback,'feedback-save':()=>{const content=$('#feedback-input').value.trim();if(!content){toast('请输入反馈内容');return;}state.feedback.push({id:uid(),version:'1.0.1',date:new Date().toISOString(),status:'本机已保存，未发送',content});state.feedback=state.feedback.slice(-40);save();closeModal();toast('反馈已保存到本机，尚未发送给开发者。');},
  'feedback-export':()=>saveText(JSON.stringify({app:'简历工坊',version:'1.0.1',feedback:state.feedback},null,2),'简历工坊_反馈.json'),
  'privacy':privacy,'help':help,'licenses':licenses,'license-read':async el=>{try{const response=await fetch('licenses/'+el.dataset.file);if(!response.ok)throw Error();openModal('开源许可','<div class="import-review" style="max-height:65vh">'+esc(await response.text())+'</div>');}catch(_){toast('许可文件随源码附带，可查看交付说明。');}},'close-modal':closeModal
 };
 function moveEntry(i,delta){const a=current().profile[module],j=i+delta;if(j<0||j>=a.length)return;[a[i],a[j]]=[a[j],a[i]];changed();render();}
 function moveSection(i,delta){const a=current().settings.sectionOrder,j=i+delta;if(j<0||j>=a.length)return;[a[i],a[j]]=[a[j],a[i]];changed();render();}
 document.addEventListener('click',e=>{const el=e.target.closest('[data-action]');if(!el||el.disabled)return;const act=el.dataset.action;if(act.startsWith('nav-'))nav(act.slice(4));else if(actions[act])actions[act](el);});
 document.addEventListener('input',e=>{const el=e.target;if(el.dataset.field){const keys=el.dataset.field.split('.');let obj=current().profile;for(const k of keys.slice(0,-1))obj=obj[k];obj[keys[keys.length-1]]=el.dataset.array?el.value.split(/[,，、;；\n]/).map(s=>s.trim()).filter(Boolean):el.value;changed();}
  if(el.id==='template-search'){query=el.value;visibleCount=24;updateGallery();}
  if(['crop-zoom','crop-x','crop-y'].includes(el.id)){const img=$('#crop-photo');img.style.transform='scale('+$('#crop-zoom').value+')';img.style.objectPosition=$('#crop-x').value+'% '+$('#crop-y').value+'%';}
 });
 document.addEventListener('change',e=>{const el=e.target;if(el.dataset.setting){const k=el.dataset.setting;current().settings[k]=el.type==='checkbox'?el.checked:['fontSize','lineHeight','margin','pageTarget'].includes(k)?+el.value:el.value;changed();refreshPreview();}
  if(el.dataset.sectionVisible){const k=el.dataset.sectionVisible;current().settings.hiddenSections=el.checked?current().settings.hiddenSections.filter(x=>x!==k):[...new Set([...current().settings.hiddenSections,k])];changed();refreshPreview();}
  if(el.id==='diagnostics-toggle'){state.diagnosticsEnabled=el.checked;save();}
 });
 $('#document-input').addEventListener('change',e=>{const f=e.target.files[0];e.target.value='';if(f)importFile(f);});
 $('#photo-input').addEventListener('change',e=>{const f=e.target.files[0];e.target.value='';if(f)choosePhoto(f);});
 document.addEventListener('visibilitychange',()=>{if(document.hidden&&state)save();});window.addEventListener('resize',bindFrames);
 window.addEventListener('error',e=>{if(state?.diagnosticsEnabled&&window.Native){try{Native.reportError(JSON.stringify({type:'javascript',page:screen,version:'1.0.1',line:e.lineno||0}));}catch(_){}}});
 load();render();save();
})();
