// Direct semantic port of formal 1.0.31 SongSearch.java / NativeCatalog.familiarFirst.
export const fold=s=>String(s||'').normalize('NFKC').toLowerCase().replace(/[^\p{L}\p{N}]/gu,'');
const familiar=['晴天','稻香','告白气球','七里香','起风了','孤勇者','花海','青花瓷','蒲公英的约定','成都','夜曲','大鱼','刻在我心底的名字','小幸运','光年之外','演员','追光者','平凡之路','往后余生','不能说的秘密','菊花台','flower dance','river flows in you','kiss the rain','faded','天空之城','千本樱','梦中的婚礼','卡农'];
const aliases=[['flower dance','花舞','花之舞'],['river flows in you','你的心河','你心中的河流'],['kiss the rain','雨的印记','雨之印记'],["baby don't cry",'人鱼的眼泪'],['always with me','いつも何度でも','永远同在']];
function rank(s){if(['儿歌','练习曲'].includes(s.category)||s.category?.startsWith('原神'))return Infinity;const title=fold(s.title),artist=fold(s.author);for(let r=0;r<familiar.length;r++){if(!title.startsWith(fold(familiar[r])))continue;if((r<=3||[6,7,8,10,19,20].includes(r))&&!artist.includes('周杰伦')&&!artist.includes('jaychou'))continue;if(r===24&&!artist.includes('alanwalker'))continue;return r;}return Infinity;}
function category(s){return ({'流行':0,'网络热门':0,'动漫':1,'影视':2,'轻音乐':3,'经典':4,'民乐':5,'儿歌':8,'练习曲':9})[s.category]??(s.category?.startsWith('原神')?7:6);}
function preference(s){const t=fold(s.title);return category(s)*1000+(t.includes('四手')||t.includes('变奏')?150:0)-(t.includes('原调')||t.includes('完整版')?30:0)+Math.min(120,t.length);}
export function nativeOrder(rows){const representatives=new Map(),ranks=new Map();for(const s of rows){const r=rank(s);ranks.set(s,r);if(r===Infinity)continue;const p=representatives.get(r);if(!p||preference(s)<preference(p))representatives.set(r,s);}const first=new Set(representatives.values()),bucket=s=>first.has(s)?0:ranks.get(s)!==Infinity?1:2;return [...rows].sort((a,b)=>bucket(a)-bucket(b)||(bucket(a)<2?ranks.get(a)-ranks.get(b):category(a)-category(b)));}
function aliasTerms(original,title){const segments=String(original).normalize('NFKC').toLowerCase().split(/[^\p{L}\p{N}]+/u);return aliases.filter(group=>group.some(member=>{const n=fold(member);return n.length>=4&&title.includes(n)||segments.includes(n);})).flatMap(g=>g.map(fold)).join(' ');}
function typo(text,query){if(query.length<4||query.length>48||!text)return 0;const limit=/\p{Script=Han}/u.test(query)?1:query.length>=7?2:1,candidate=text.slice(0,96);if(candidate.length<query.length-limit)return 0;let shared=0;for(let i=0;i+1<query.length;i++)if(candidate.includes(query.slice(i,i+2)))shared++;if(shared<Math.max(2,Math.floor((query.length-1)/2)))return 0;let previous=Array.from({length:query.length+1},(_,i)=>i),best=query.length;for(const char of candidate){const current=[0];for(let j=1;j<=query.length;j++)current[j]=Math.min(previous[j-1]+(query[j-1]===char?0:1),previous[j]+1,current[j-1]+1);best=Math.min(best,current[query.length]);previous=current;}return best<=limit?500-best*70:0;}
function score(s,raw){const q=fold(raw);if(!q)return 1;const t=fold(s.title),a=fold(s.author),c=fold(s.category),aliases=aliasTerms(s.title,t);if(t===q)return 1600;if(t.startsWith(q))return 1400;if(t.includes(q))return 1200;if(aliases.includes(q))return 1100;if(a===q)return 1000;if(a.includes(q))return 950;const tokens=String(raw).normalize('NFKC').toLowerCase().split(/[^\p{L}\p{N}]+/u).filter(Boolean),multi=tokens.length>1&&tokens.length<=8&&tokens.every(x=>x.length>=2),contains=x=>[t,a,c,aliases].some(v=>v.includes(x));if(multi&&tokens.every(contains))return 800+Math.min(80,tokens.length*10);if(c.includes(q))return 650;if(!multi)return Math.max(typo(t,q),typo(a,q),typo(aliases,q));let miss=false;for(const token of tokens){if(contains(token))continue;if(!Math.max(typo(t,token),typo(a,token),typo(aliases,token)))return 0;miss=true;}return miss?350:0;}
export function nativeSearch(rows,query){return rows.map((s,index)=>({s,index,score:score(s,query)})).filter(r=>r.score>0).sort((a,b)=>b.score-a.score||a.index-b.index).map(r=>r.s);}
