import {settings as surfaceSettings} from './native-surfaces.js';
import {configurePad} from './native-pad.js';
import * as formal from './native-synth.js';
const q=s=>document.querySelector(s),dialog=document.createElement('dialog');dialog.id='native-tools';document.body.append(dialog);
function sheet(title){PianoWeb.pause();dialog.innerHTML='<div class="dialog-head"><h2></h2><button>完成</button></div><div class="native-tool-body"></div>';dialog.querySelector('h2').textContent=title;dialog.querySelector('.dialog-head button').onclick=()=>dialog.close();if(!dialog.open)dialog.showModal();return dialog.querySelector('.native-tool-body');}
function button(parent,label,fn){const b=document.createElement('button');b.textContent=label;b.onclick=fn;parent.append(b);return b;}
function selector(parent,label,values,current,onchange){const row=document.createElement('label');row.className='setting';row.append(document.createTextNode(label));const select=document.createElement('select');for(const [value,name]of values)select.add(new Option(name,String(value)));select.value=String(current);select.onchange=()=>onchange(select.value);row.append(select);parent.append(row);return select;}
function control(parent,id,label){const original=q('#'+id),row=document.createElement('label');row.className='setting';row.append(document.createTextNode(label));const copy=original.cloneNode(true);copy.removeAttribute('id');copy.value=original.value;copy.checked=original.checked;copy.oninput=()=>{original.value=copy.value;original.dispatchEvent(new Event('input'));};copy.onchange=()=>{original.value=copy.value;original.checked=copy.checked;original.dispatchEvent(new Event('change'));};row.append(copy);parent.append(row);return copy;}
function layout(){const surface=App31Surfaces.inspect().surface,p=sheet(({calculator:'计算器布局与谱面',handheld:'音乐掌机',visualizer:'音乐可视化',pad:'打击垫声音与灯光',scope:'科学仪器旋钮与谱面'})[surface]||'乐器演奏与音域');
 if(surface==='calculator'){let count=App31Surfaces.inspect().calcCount,numbered=App31Surfaces.inspect().numbered;selector(p,'按键数量',[[9,'9 键 · 3×3 · 大按键入门'],[12,'12 键 · 3×4 · 十二音级'],[16,'16 键 · 4×4 · 原计算器布局']],count,v=>surfaceSettings().configureCalculator(count=Number(v),numbered));selector(p,'谱面',[[0,'按键谱'],[1,'简谱']],numbered?1:0,v=>surfaceSettings().configureCalculator(count,numbered=v==='1'));}
 else if(surface==='handheld'){let{shape,game}=App31Surfaces.inspect();selector(p,'掌机外形',['双侧掌机 · 全白横屏','复古掌机 · 竖屏','迷你掌机 · 横屏','双屏掌机 · 竖屏','街机面板 · 横屏'].map((v,i)=>[i,v]),shape,v=>surfaceSettings().configureHandheld(shape=Number(v),game));selector(p,'小游戏',['跳台阶','接星星','节奏赛车','俄罗斯方块','飞船射击','旋律花园','数字合并','旋律贪吃蛇','音符打砖块'].map((v,i)=>[i,v]),game,v=>surfaceSettings().configureHandheld(shape,game=Number(v)));}
 else if(surface==='visualizer')selector(p,'谱面风格',[[0,'流光谱面 · 紫色旋律与金色低音'],[1,'清晰谱面 · 正面双行五线谱']],App31Surfaces.inspect().style,v=>surfaceSettings().configureVisualizer(Number(v)));
 else if(surface==='pad'){let {count,percussion,effect}=App31Pad.inspect().configuration;selector(p,'按键数量',[[9,'9 键 · 3×3'],[16,'16 键 · 4×4']],count,v=>configurePad(count=Number(v),percussion,effect));selector(p,'演奏声音',[[1,'电子鼓组'],[0,'旋律音色']],percussion?1:0,v=>{percussion=v==='1';configurePad(count,percussion,effect);if(!percussion)q('#tone-entry').click();});selector(p,'灯光效果',[[0,'轻量击打光环'],[1,'多彩击打'],[2,'星光击打']],effect,v=>configurePad(count,percussion,effect=Number(v)));}
 else if(surface==='scope'){let count=9,advanced=false,timebase=3,gain=1,frozen=false;const configure=()=>App31Scope.configure(count,advanced,timebase,gain,frozen);selector(p,'按键数量',[[9,'9 键 · 一至九'],[12,'12 键'],[16,'16 键']],count,v=>{count=Number(v);configure();});selector(p,'操作面板',[[0,'简单模式'],[1,'显示专业旋钮']],0,v=>{advanced=v==='1';configure();});selector(p,'波形时间范围',[[0,'1 ms'],[1,'2 ms'],[2,'5 ms'],[3,'10 ms'],[4,'20 ms'],[5,'50 ms']],timebase,v=>{timebase=Number(v);configure();});}
 button(p,'音色与音量',volume);control(p,'simple','简单弹奏，音长自动补足');button(p,'查看整页简谱 / 五线谱',()=>{dialog.close();q('#score').click();});}
function volume(){const p=sheet('音色与音量');button(p,'选择音色',()=>{dialog.close();q('#tone-entry').click();});control(p,'volume','音量');control(p,'sustain','默认延音');}
let guitarState={enabled:false,chord:0,pattern:0,bpm:60,measures:8,demonstration:false};
function guitar(){const p=sheet('节奏与扫弦'),apply=()=>formal.guitarConfigure(guitarState.enabled,guitarState.chord,guitarState.pattern,guitarState.bpm,guitarState.measures,guitarState.demonstration);selector(p,'练习面板',[[0,'指板弹奏'],[1,'节奏与扫弦']],guitarState.enabled?1:0,value=>{guitarState.enabled=value==='1';apply();});selector(p,'和弦',['C','G','Am','F','D','Em'].map((name,i)=>[i,name]),guitarState.chord,value=>{guitarState.chord=Number(value);apply();});selector(p,'节奏型',[[0,'八分扫弦'],[1,'切音型']],guitarState.pattern,value=>{guitarState.pattern=Number(value);apply();});selector(p,'BPM',Array.from({length:121},(_,i)=>[40+i,String(40+i)]),guitarState.bpm,value=>{guitarState.bpm=Number(value);apply();});selector(p,'练习长度',[[1,'1 小节'],[4,'4 小节'],[8,'8 小节'],[16,'16 小节']],guitarState.measures,value=>{guitarState.measures=Number(value);apply();});selector(p,'弹奏方式',[[0,'自己练习'],[1,'自动示范']],guitarState.demonstration?1:0,value=>{guitarState.demonstration=value==='1';apply();});button(p,'开始扫弦练习',async()=>{guitarState.enabled=true;apply();await PianoWeb.audio.prepare([40,45,50,55,59,64]);dialog.close();formal.guitarAction(0);});button(p,'暂停练习',()=>formal.guitarAction(1));button(p,'从头，等待开始',()=>formal.guitarAction(2));}
function width(){const p=sheet('琴键宽度');const range=control(p,'key-count','显示白键数量');range.replaceChildren(...Array.from({length:16},(_,i)=>new Option((i+7)+' 白键',String(i+7))));range.value=q('#key-count').value;}
function range(){const p=sheet('键盘音域');const strip=document.createElement('div');strip.className='native-mini-keyboard';for(let pitch=21;pitch<=108;pitch++){if([1,3,6,8,10].includes(pitch%12))continue;button(strip,'',()=>PianoWeb.setRange(pitch)).setAttribute('aria-label','音域起点 MIDI '+pitch);}p.append(strip);button(p,'低一个八度',()=>q('#lower').click());button(p,'高一个八度',()=>q('#higher').click());button(p,'琴键数量',width);const drag=document.createElement('label');drag.className='setting';drag.textContent='直接拖动琴键调整音域';const check=document.createElement('input');check.type='checkbox';check.checked=PianoWeb.inspect().keyboardDrag;check.onchange=()=>PianoWeb.setDrag(check.checked);drag.append(check);p.append(drag);}
function progress(){dialog.close();q('#progress-entry').click();}
function practice(){const p=sheet('跟弹设置');for(const [key,label] of [['autoHelp','超过时间自动补奏'],['adaptive','根据反应速度调整缓冲']]){const row=document.createElement('label');row.className='setting';row.textContent=label;const check=document.createElement('input');check.type='checkbox';check.checked=PianoWeb.practiceOptions[key];check.onchange=()=>PianoWeb.practiceOptions[key]=check.checked;row.append(check);p.append(row);}selector(p,'等待上限',[[500,'0.5 秒'],[1000,'1 秒'],[1800,'1.8 秒'],[3000,'3 秒'],[5000,'5 秒']],PianoWeb.practiceOptions.maximum,v=>PianoWeb.practiceOptions.maximum=Number(v));control(p,'simple','右手＋伴奏，轻点自动补足音长');control(p,'preview','显示下一键淡轮廓');button(p,'弹奏方式',()=>{dialog.close();q('#mode-entry').click();});}
function chords(){const p=sheet('一指和弦');for(const [i,label,pitches]of [[0,'C 大三和弦',[60,64,67]],[1,'D 小三和弦',[62,65,69]],[2,'E 小三和弦',[64,67,71]],[3,'F 大三和弦',[65,69,72]],[4,'G 大三和弦',[67,71,74]],[5,'A 小三和弦',[69,72,76]]]){const b=button(p,label,()=>{});b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);pitches.forEach((pitch,n)=>PianoWeb.press('chord-'+i+'-'+n,pitch));};const release=()=>pitches.forEach((_,n)=>PianoWeb.release('chord-'+i+'-'+n));b.onpointerup=release;b.onpointercancel=release;b.onlostpointercapture=release;}dialog.addEventListener('close',()=>{for(let i=0;i<6;i++)for(let n=0;n<3;n++)PianoWeb.release('chord-'+i+'-'+n);},{once:true});}
let metronomeTimer=0,bpm=100,beat=0;function metronome(){const p=sheet('节拍器'),label=document.createElement('label');label.className='setting';label.textContent='开启节拍器';const enabled=document.createElement('input');enabled.type='checkbox';enabled.checked=!!metronomeTimer;enabled.onchange=async()=>{clearInterval(metronomeTimer);metronomeTimer=0;if(enabled.checked){await PianoWeb.audio.unlock();metronomeTimer=setInterval(()=>PianoWeb.audio.node.port.postMessage({type:'tick',accent:beat++%4===0}),60000/bpm);}};label.append(enabled);p.append(label);selector(p,'BPM · 4/4',Array.from({length:201},(_,i)=>[40+i,String(40+i)]),bpm,v=>{bpm=Number(v);if(enabled.checked)enabled.onchange();});}
function loop(){const p=sheet('A–B 循环'),s=PianoWeb.view(),state=PianoWeb.loop(),enabled=document.createElement('input');enabled.type='checkbox';enabled.checked=state.enabled;const row=document.createElement('label');row.className='setting';row.textContent='循环练习 / 播放';row.append(enabled);p.append(row);const fields=[];for(const [label,value]of [['A 起点（秒）',state.a/1000],['B 终点（秒）',(state.b||s.song.durationMs)/1000]]){const r=document.createElement('label');r.className='setting';r.textContent=label;const n=document.createElement('input');n.type='number';n.step='.1';n.min='0';n.value=value;r.append(n);p.append(r);fields.push(n);}const error=document.createElement('p');p.append(error);button(p,'应用',()=>{try{PianoWeb.loop(enabled.checked,Number(fields[0].value)*1000,Number(fields[1].value)*1000);dialog.close();}catch(e){error.textContent=e.message;}});}
function save(name,bytes,type){const url=URL.createObjectURL(new Blob([bytes],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),3000);}
function midi(){const p=sheet('曲谱文件与 MIDI');button(p,'导入 MIDI / EOP / 曲谱 JSON',()=>q('#import').click());button(p,'导出当前曲谱 MIDI',()=>{const s=PianoWeb.view().song,m=new window.Midi();m.name=s.title;m.header.setTempo(s.bpm);const track=m.addTrack();for(const n of s.notes)track.addNote({midi:n.pitch,time:n.start/1000,duration:n.duration/1000,velocity:(n.velocity||85)/127});save(s.title+'.mid',m.toArray(),'audio/midi');});button(p,'连接外部 MIDI 键盘',async()=>{try{if(!navigator.requestMIDIAccess)throw Error('此浏览器不支持 Web MIDI');const access=await navigator.requestMIDIAccess({sysex:false}),inputs=[...access.inputs.values()];if(!inputs.length)throw Error('尚未连接 MIDI 键盘');for(const input of inputs)button(p,input.name,async()=>{await input.open();input.onmidimessage=e=>{const[status,pitch,velocity]=e.data,kind=status&240,id='midi-'+input.id+'-'+(status&15)+'-'+pitch;if(kind===144&&velocity>0)PianoWeb.press(id,pitch);else if(kind===128||kind===144)PianoWeb.release(id);};});}catch(e){const error=document.createElement('p');error.textContent=e.message;p.append(error);}});}
function info(){const p=sheet(PianoWeb.view().song.title),s=PianoWeb.view().song,text=document.createElement('p');text.textContent=(s.subtitle||'')+' · '+s.notes.length+' 个音符 · '+(s.durationMs/1000).toFixed(1)+' 秒';p.append(text);button(p,'查看简谱',()=>{dialog.close();q('#score').click();});}
export function tools(){const p=sheet('演奏工具');button(p,'查看整页简谱 / 五线谱',()=>{dialog.close();q('#score').click();});if(App31Surfaces.inspect().surface!=='piano')button(p,'乐器布局与谱面',layout);button(p,'导出当前歌曲 WAV',async()=>{try{const{exportActualWav}=await import('./native-video.js');const blob=await exportActualWav();save(PianoWeb.view().song.title+'.wav',blob,'audio/wav');}catch(error){q('#status').textContent=error.message;}});button(p,'只录音符，保存到我的曲目',()=>{dialog.close();q('#record').click();});for(const [title,items]of [['声音与节拍',[['音色与音量',volume],['节拍器',metronome],['一指和弦',chords],['MIDI 与键盘',midi]]],['键盘与跟弹',[['琴键宽度',width],['音域滑动与拖动',range],['跟弹设置',practice]]],['曲目与录制',[['速度与进度',progress],['A–B 循环',loop],['我的录制',()=>{dialog.close();q('#category').value='录制';q('#library').click();}],['曲目信息',info]]]]){const group=document.createElement('section');group.className='native-tool-section';const h=document.createElement('h3');h.textContent=title;group.append(h);for(const [label,action]of items)button(group,label+' ›',action);p.append(group);}}
q('#settings').onclick=tools;q('#range-entry').onclick=range;
const guitarEntry=document.createElement('button');guitarEntry.id='native-guitar-entry';guitarEntry.textContent='扫弦';guitarEntry.onclick=guitar;q('.native-commands').append(guitarEntry);setInterval(()=>{const preset=Number(q('#tone').value);guitarEntry.hidden=App31Surfaces.inspect().surface!=='touch'||!([6,7].includes(preset)||preset>=58&&preset<=65);},100);
const originalStart=q('#start').onclick;q('#start').onclick=async()=>{if(formal.guitarEnabled()){await PianoWeb.audio.prepare([40,45,50,55,59,64]);formal.guitarAction(formal.guitarRunning()?1:0);q('#start').textContent=formal.guitarRunning()?'暂停':'开始';}else originalStart();};
let collapseEnabled=false,expandedDuringPlay=false;const expand=document.createElement('button');expand.id='native-expand-controls';expand.textContent='展开控制栏';expand.hidden=true;q('.native-toolbar').append(expand);expand.onclick=()=>{expandedDuringPlay=true;document.body.classList.remove('chrome-collapsed');expand.hidden=true;};setInterval(()=>{const playing=PianoWeb.inspect().playing||formal.guitarRunning();if(!playing)expandedDuringPlay=false;const collapsed=collapseEnabled&&playing&&!expandedDuringPlay;document.body.classList.toggle('chrome-collapsed',collapsed);expand.hidden=!collapsed;},100);
const originalTools=q('#settings').onclick;q('#settings').onclick=()=>{originalTools();const body=dialog.querySelector('.native-tool-body'),row=document.createElement('label');row.className='setting';row.textContent='弹奏时收起操作栏（默认关闭）';const check=document.createElement('input');check.type='checkbox';check.checked=collapseEnabled;check.onchange=()=>{collapseEnabled=check.checked;expandedDuringPlay=false;};row.append(check);body.append(row);};
const games=document.createElement('button');games.id='native-game-entry';games.textContent='游戏 ▾';games.onclick=layout;q('#mode-entry').after(games);setInterval(()=>{games.hidden=App31Surfaces.inspect().surface!=='handheld';},100);
q('#key-count').replaceChildren(...Array.from({length:16},(_,i)=>new Option(String(i+7),String(i+7))));q('#key-count').value=String(PianoWeb.inspect().keyCount);
const speed=q('#speed').closest('label');q('#native-progress .position').after(speed);
