import {bindCanvasKeyboard} from './native-canvas-pc.js';
let unbindPc=null;
import * as formal from './native-synth.js';
let canvas=null,loop=0,lastError='',frameTimes=[],lastAt=0;
let configuration={count:16,percussion:true,effect:0};
export function openPad(){closePad();canvas=document.createElement('canvas');canvas.id='native-pad-canvas';canvas.setAttribute('aria-label','多彩打击垫，可同时按多个格');document.querySelector('.instrument').append(canvas);unbindPc=bindCanvasKeyboard(canvas,0,formal.padPointer);formal.padConfigure(configuration.count,configuration.percussion,configuration.effect);
 const activePointers=new Set();
 const input=(event,action)=>{event.preventDefault();const r=canvas.getBoundingClientRect();formal.padPointer(action,event.pointerId,event.clientX-r.left,event.clientY-r.top);};
 canvas.onpointerdown=e=>{activePointers.add(e.pointerId);canvas.setPointerCapture(e.pointerId);input(e,0);};canvas.onpointermove=e=>{if(canvas.hasPointerCapture(e.pointerId))input(e,2);};canvas.onpointerup=e=>{if(!activePointers.delete(e.pointerId))return;input(e,1);if(canvas.hasPointerCapture(e.pointerId))canvas.releasePointerCapture(e.pointerId);};canvas.onpointercancel=e=>{activePointers.clear();input(e,3);};canvas.onlostpointercapture=e=>{if(activePointers.delete(e.pointerId))input(e,1);};
 const draw=at=>{if(!canvas)return;try{const r=canvas.getBoundingClientRect(),d=devicePixelRatio;if(canvas.width!==Math.round(r.width*d)||canvas.height!==Math.round(r.height*d)){canvas.width=Math.round(r.width*d);canvas.height=Math.round(r.height*d);}const c=canvas.getContext('2d');c.setTransform(d,0,0,d,0,0);const s=PianoWeb.view();formal.padDraw(c,Math.round(r.width),Math.round(r.height),s.mode==='free'?0:s.mode==='auto'?1:2,s.position,s.active.map(n=>n.pitch).join(','),s.speed);if(lastAt)frameTimes.push(at-lastAt);lastAt=at;if(frameTimes.length>120)frameTimes.shift();loop=requestAnimationFrame(draw);}catch(e){lastError=e.message;document.querySelector('#status').textContent=e.message;}};loop=requestAnimationFrame(draw);
}
export function closePad(){unbindPc?.();unbindPc=null;cancelAnimationFrame(loop);if(canvas){formal.padPointer(3,0,0,0);canvas.remove();canvas=null;}lastAt=0;}
export function configurePad(count,percussion,effect){const changed=configuration.percussion!==percussion;configuration={count,percussion,effect};formal.padConfigure(count,percussion,effect);if(changed){const tone=document.querySelector('#tone');tone.value=String(percussion?29:17);tone.dispatchEvent(new Event('change'));}PianoWeb.audio.sustain=!percussion&&document.querySelector('#sustain').checked;}
window.App31Pad={inspect(){return{open:!!canvas,error:lastError,configuration:{...configuration},frames:frameTimes.length,averageFrameMs:frameTimes.reduce((a,b)=>a+b,0)/Math.max(1,frameTimes.length)};},configure:configurePad};
