import {bindCanvasKeyboard} from './native-canvas-pc.js';
let unbindPc=null;
import * as formal from './native-synth.js';let canvas=null,loop=0,sequence=-1,error='';
export function openScope(){closeScope();canvas=document.createElement('canvas');canvas.id='native-scope-canvas';canvas.setAttribute('aria-label','音乐仪器，一至九演奏按键，真实声音波形');document.querySelector('.instrument').append(canvas);unbindPc=bindCanvasKeyboard(canvas,2,formal.scopePointer);
 const activePointers=new Set();
 const input=(e,action)=>{e.preventDefault();const r=canvas.getBoundingClientRect();formal.scopePointer(action,e.pointerId,e.clientX-r.left,e.clientY-r.top);};canvas.onpointerdown=e=>{activePointers.add(e.pointerId);canvas.setPointerCapture(e.pointerId);input(e,0);};canvas.onpointermove=e=>{if(canvas.hasPointerCapture(e.pointerId))input(e,2);};canvas.onpointerup=e=>{if(!activePointers.delete(e.pointerId))return;input(e,1);if(canvas.hasPointerCapture(e.pointerId))canvas.releasePointerCapture(e.pointerId);};canvas.onpointercancel=e=>{activePointers.clear();input(e,3);};canvas.onlostpointercapture=e=>{if(activePointers.delete(e.pointerId))input(e,1);};
 const draw=()=>{if(!canvas)return;try{const r=canvas.getBoundingClientRect(),d=devicePixelRatio;if(canvas.width!==Math.round(r.width*d)||canvas.height!==Math.round(r.height*d)){canvas.width=Math.round(r.width*d);canvas.height=Math.round(r.height*d);}const c=canvas.getContext('2d');c.setTransform(d,0,0,d,0,0);const s=PianoWeb.view(),audio=PianoWeb.audio;if(audio.pcm&&sequence!==audio.pcmSequence){sequence=audio.pcmSequence;formal.scopePcm(audio.pcm);}formal.scopeDraw(c,Math.round(r.width),Math.round(r.height),Number(document.querySelector('#tone').value),s.mode==='free'?0:s.mode==='auto'?1:2,s.position,s.active.map(n=>n.pitch).join(','),s.speed,audio.volume);loop=requestAnimationFrame(draw);}catch(e){error=e.message;document.querySelector('#status').textContent=e.message;}};loop=requestAnimationFrame(draw);
}
export function closeScope(){unbindPc?.();unbindPc=null;cancelAnimationFrame(loop);if(canvas){formal.scopePointer(3,0,0,0);canvas.remove();canvas=null;}}
window.App31Scope={inspect(){return{open:!!canvas,error,pcmSequence:sequence};},configure:formal.scopeConfigure};
