'use strict';
// Faithful presentation port of SleepUi.kt 1.1.2. Never reads or transmits native data.
const KEY='mianji-html-parity-1.1.2-v1';let saved;try{saved=JSON.parse(localStorage.getItem(KEY))}catch{};
let data=saved||{enabled:true,granted:false,target:480,records:[],feedback:[],diagnostics:false,autoUpdate:true};let tab=0,days=7,selected=6,demo=false,menu=null;const scrolls=[0,0,0];
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const localDate=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`,clock=ms=>new Date(ms).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit',hour12:false}),fullDate=d=>new Date(d+'T12:00:00').toLocaleDateString('zh-CN',{year:'numeric',month:'long',day:'numeric'}),dateLabel=d=>`${new Date(d+'T12:00').getMonth()+1}月${new Date(d+'T12:00').getDate()}日`,short=m=>m<60?`${m}分`:`${Math.floor(m/60)}小时${m%60?`${m%60}分`:''}`,duration=m=>`<div class="duration">${Math.floor(m/60)}<small>小时</small>${String(m%60).padStart(2,'0')}<small>分</small></div>`;
const paths={moon:'M20.8 13.3A8.5 8.5 0 0 1 10.7 3.2 8.5 8.5 0 1 0 20.8 13.3Z',chart:'M4 19V9h3v10M10 19V4h3v15M16 19v-7h3v7',person:'M16 7a4 4 0 1 1-8 0 4 4 0 0 1 8 0ZM4 21v-2a8 8 0 0 1 16 0v2Z',shield:'M12 2 3 6v6c0 5 9 10 9 10s9-5 9-10V6ZM8 12l3 3 5-6',clock:'M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0ZM12 7v5l3 2',download:'M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5',save:'M4 3h13l4 4v14H3V3h1ZM7 3v6h10V3M7 21v-7h10v7',restore:'M3 10a9 9 0 1 1 2 8M3 3v7h7M12 7v5l4 2',bug:'M8 5l-2-2m10 2 2-2M8 7h8v11a4 4 0 0 1-8 0ZM3 10h5m8 0h5M3 15h5m8 0h5',delete:'M4 7h16M9 7V3h6v4M6 7l1 14h10l1-14M10 10v8m4-8v8',mail:'M3 5h18v14H3ZM3 5l9 7 9-7',refresh:'M20 8a8 8 0 1 0 1 8M20 3v6h-6',info:'M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0ZM12 11v6m0-10v1',open:'M14 3h7v7m0-7L10 14M10 3H3v18h18v-7',check:'M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0ZM7 12l3 3 7-7'};
const icon=k=>`<svg class="icon" viewBox="0 0 24 24" aria-hidden="true">${officialIcons[k]||`<path d="${paths[k]||paths.info}"/>`}</svg>`;
const moon=(size=100)=>`<svg class="moon" viewBox="0 0 100 100" style="width:${size}px;height:${size}px" aria-label="一弯安静的月亮"><circle cx="48" cy="50" r="46.5" fill="white" opacity=".35"/><circle cx="48" cy="50" r="30" fill="#8b82a1"/><circle cx="65.1" cy="41" r="27.3" fill="#e9e6f0"/><path d="M75 23h6m-3-3v6M18 18h4m-2-2v4M77 73h4m-2-2v4" stroke="#8b82a1" stroke-width="1.4" stroke-linecap="round"/></svg>`;
function persist(){try{localStorage.setItem(KEY,JSON.stringify(data))}catch{toast('浏览器未允许保存，当前演示只保留到关闭页面。')}}
function toast(s){$('#toast').textContent=s;$('#toast').style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').style.display='none',4200)}
function samples(){return [435,467,402,482,448,425,476,461,455,391,472,459,421,466].map((m,i)=>{let end=new Date();end.setDate(end.getDate()-i);end.setHours(7,15+(i%4)*5,0,0);return{id:'demo-'+i,date:localDate(end),end:+end,start:+end-m*60000,minutes:m-(i===2?8:0),phoneUse:i===2?8:0,quality:3+(i%3-1),note:'',confirmed:true,excluded:false,source:'示例',reason:'独立示例，非你的睡眠数据'}})}
function records(){return (demo?samples():data.records).slice().sort((a,b)=>b.end-a.end)}
function render(){const rs=records();$('#page').innerHTML=`<header><h1>${['眠迹','睡眠趋势','我的眠迹'][tab]}</h1><p>${[new Date().toLocaleDateString('zh-CN',{month:'long',day:'numeric',weekday:'long'}).replace(/(\d日)/,'$1 '),'时长与每日作息','作息设置与本地数据'][tab]}</p></header>${demo?`<div class="banner item">${icon('visibility')}<div style="flex:1"><b>正在查看示例</b><small>虚构数据，不会保存为你的记录</small></div><button class="textbtn" data-act="exit-demo">退出</button></div>`:''}${[home,trend,profile][tab](rs)}`;$('#nav').innerHTML=['监测','趋势','我的'].map((s,i)=>`<button class="${i===tab?'active':''}" data-tab="${i}" aria-current="${i===tab?'page':'false'}"><span class="icon-wrap">${icon(['moon','chart','person'][i])}</span>${s}</button>`).join('');$('#page').scrollTop=scrolls[tab]}
function home(rs){const r=rs.find(x=>!x.excluded);let h;if(!r){let active=data.granted&&data.enabled;h=`<div class="empty item">${moon()}<h2>${active?'正在自动监测':!data.granted?'开启你的睡眠记录':'监测已暂停'}</h2><p class="muted">${active?'照常使用手机，醒来后查看记录。':'只需首次授权，之后自动整理。'}</p>${active?'<div class="indicator"><i class="dot"></i>后台记录中</div><div class="caption">暂无完整休息记录</div>':'<button class="primary" data-act="enable">一键开启</button>'}</div>`}else h=`<section class="hero item" ${demo?'':`data-edit="${esc(r.id)}" role="button" tabindex="0" aria-label="修改与确认记录"`}><div class="row between"><span class="muted" style="font-size:13px">${dateLabel(r.date)} · ${r.confirmed?'已确认':'睡眠估算'}</span>${moon(55)}</div>${duration(r.minutes)}<div class="metrics"><div><small>开始</small><b>${clock(r.start)}</b></div><span class="muted">···</span><div><small>结束</small><b>${clock(r.end)}</b></div><div><small>目标</small><b>${short(data.target)}</b></div></div><div class="progress"><i style="width:${Math.min(r.minutes/data.target,1)*100}%"></i></div><div class="row between status"><span>${r.minutes>=data.target?'已达到你的时长目标':'距目标 '+short(data.target-r.minutes)}</span><span>${r.confirmed?'已确认':'待确认'}</span></div><p class="muted" style="font-size:12px;line-height:18px">${esc(r.reason)}</p>${r.phoneUse?`<p class="privacy" style="margin-top:6px">这段区间内使用手机 ${r.phoneUse} 分钟，已从估算时长扣除。</p>`:''}${!demo?'<div class="hint">轻触记录可校正</div>':''}</section><div class="card item monitorcard"><div class="row">${icon('phone')}<div><b style="font-weight:500">${demo?'这是示例中的睡眠记录':data.enabled?'自动记录已开启':'自动记录已暂停'}</b><p>${demo?'退出示例后，可以开始自己的第一晚。':'网页版演示不读取手机使用事件；补记只保存在本浏览器。'}</p></div></div></div>`;return h+'<p class="privacy item">根据手机使用间隔估计休息时间，不能测量真实入睡或睡眠阶段。</p>'}
function daily(rs){const today=localDate(new Date()),from=new Date(today+'T12:00');from.setDate(from.getDate()-days+1);const map=new Map();for(const r of rs){if(r.excluded||r.date<localDate(from)||r.date>today)continue;if(!map.has(r.date)||map.get(r.date).minutes<r.minutes)map.set(r.date,r)}return map}
function chart(map){const upper=Math.ceil(Math.max(600,data.target+60,...[...map.values()].map(r=>r.minutes+60))/120)*120;const w=Math.max(180,Math.min(480,document.documentElement.clientWidth)-88),l=32,right=w-8,top=8,bottom=208,step=(right-l)/days;let svg='';for(let m=0;m<=upper;m+=120){const y=bottom-200*m/upper;svg+=`<line x1="${l}" x2="${right}" y1="${y}" y2="${y}" stroke="#ece8e3"/><text x="0" y="${y+3}">${m/60}</text>`}svg+=`<line x1="${l}" x2="${right}" y1="${bottom-200*data.target/upper}" y2="${bottom-200*data.target/upper}" stroke="#b5abc6" stroke-width="1.4" stroke-dasharray="6 4"/><line x1="${l+step*(selected+.5)}" x2="${l+step*(selected+.5)}" y1="8" y2="208" stroke="#373346" opacity=".18"/>`;let dates=[];for(let i=0;i<days;i++){const d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()-days+1+i);const date=localDate(d),x=l+step*(i+.5),r=map.get(date);dates.push(date);if(r){const y=bottom-200*r.minutes/upper,c=r.confirmed?'#668e86':'#aba3be';svg+=`<line x1="${x}" x2="${x}" y1="208" y2="${y}" stroke="${c}" stroke-opacity="${i===selected?.85:.45}" stroke-width="${Math.min(step*.5,18)}"/><circle cx="${x}" cy="${y}" r="${days===7?4:2.5}" fill="${r.confirmed?c:'white'}" stroke="${c}" stroke-width="1.5"/>`}else svg+=`<line x1="${x-2}" x2="${x+2}" y1="213" y2="213" stroke="#777281" opacity=".5"/>`;if(days===7||[0,7,14,21,29].includes(i)){let label=`${d.getMonth()+1}/${d.getDate()}`;svg+=`<text x="${Math.min(right-label.length*5/2,Math.max(l+label.length*5/2,x))}" y="231" text-anchor="middle">${label}</text>`}svg+=`<rect x="${l+step*i}" y="0" width="${step}" height="240" fill="transparent" data-day="${i}" role="button" tabindex="0" aria-label="查看${dateLabel(date)}"/>`}
const d=dates[selected],r=map.get(d);return `<div class="chart-title"><span>每日休息时长</span><small>小时</small></div><svg class="chart" viewBox="0 0 ${w} 240" aria-label="近${days}天休息时长，纵轴0至${upper/60}小时">${svg}</svg><div class="chart-detail"><p>${fullDate(d)}</p><b>${r?short(r.minutes)+' · '+(r.confirmed?'已确认':'待确认'):'无记录 · 不计入平均值'}</b>${r?`<p class="times">${clock(r.start)} — ${clock(r.end)}</p>`:''}</div><p class="muted" style="font-size:10px;margin-top:8px">轻触图表查看某一天</p>`}
function trend(rs){const map=daily(rs),r=[...map.values()],mean=r.length?Math.trunc(r.reduce((s,x)=>s+x.minutes,0)/r.length):null;const ordered=r.slice().sort((a,b)=>a.start-b.start),mins=x=>new Date(x.start).getHours()*60+new Date(x.start).getMinutes();const variation=r.length<3?null:Math.trunc(ordered.slice(1).reduce((s,x,i)=>{let delta=Math.abs(mins(x)-mins(ordered[i]));return s+Math.min(delta,1440-delta)},0)/(r.length-1));return `<div class="item"><div class="chips">${[7,30].map(n=>`<button class="chip ${days===n?'selected':''}" data-range="${n}" aria-pressed="${days===n}">近${n}天</button>`).join('')}</div><section class="card"><p class="average">平均休息时长</p><div style="margin-top:10px">${mean===null?'<span style="font-size:38px;font-weight:300;display:block;height:45px;line-height:45px">—</span>':duration(mean)}</div><p class="muted" style="font-size:12px;margin-top:8px">${r.length} 个有记录的日期 / 近${days}天</p><div class="chartarea">${chart(map)}</div><div class="row muted" style="font-size:10px;margin-top:12px"><span style="color:var(--teal)">● 已确认</span><span>○ 待确认</span><span>— — 目标</span></div><p class="privacy" style="margin-top:11px">每天取最长一段睡眠；缺失日期留空，不按零小时计算。</p></section><div class="stats"><div class="stat"><label>达到目标</label><b>${r.length?r.filter(x=>x.minutes>=data.target).length+' / '+r.length+' 晚':'—'}</b><small>按你的时长目标</small></div><div class="stat"><label>开始时间波动</label><b>${variation===null?'—':variation+' 分'}</b><small>${variation===null?'至少需要 3 晚记录':'相邻记录平均差'}</small></div></div>${r.length<3?'<p class="muted" style="font-size:12px;line-height:20px;margin-top:18px">样本还少，暂时无法判断作息规律。多记几晚，再看变化。</p>':''}</div><div class="row between item"><h2>睡眠日记</h2>${demo?'':'<button class="textbtn" data-act="add">补记</button>'}</div>${rs.length?rs.map(r=>`<div class="diary" style="${r.excluded?'background:#f0ede8':''}"><button class="body" ${demo?'disabled':`data-edit="${esc(r.id)}"`}><h3>${dateLabel(r.date)}<span class="tag">${r.excluded?'不计入统计':r.confirmed?'已确认':'待确认'}</span></h3><p>${clock(r.start)} – ${clock(r.end)} · ${r.source}</p>${r.note?`<p>${esc(r.note)}</p>`:''}</button><strong>${short(r.minutes)}</strong>${demo?'<span style="width:12px"></span>':`<button class="more" data-menu="${esc(r.id)}" aria-label="${dateLabel(r.date)}的记录操作">⋮</button>`}</div>`).join(''):'<div class="card"><h2>还没有你的睡眠记录</h2><p class="muted" style="margin-top:8px;font-size:13px">自动生成记录后，趋势会在这里显示。</p></div>'}`}
function action(k,title,subtitle,act,disabled=false,danger=false){return `<button class="setting ${danger?'danger':''}" data-act="${act}" ${disabled?'disabled':''}>${icon(k)}<span class="body"><b>${title}</b><small>${subtitle}</small></span><span class="muted">›</span></button>`}
function switchRow(k,title,subtitle,key,on){return `<div class="setting">${icon(k)}<span class="body"><b>${title}</b><small>${subtitle}</small></span><button class="switch ${on?'on':''}" role="switch" aria-label="${title}" aria-checked="${on}" data-switch="${key}" ${demo?'disabled':''}></button></div>`}
function group(title,rows){return `<section class="item"><h2>${title}</h2><div class="card settings">${rows.join('<hr>')}</div></section>`}
function profile(rs){return `<div class="summary item"><div class="avatar">${icon('avatar')}</div><div><b>${demo?'示例睡眠记录':rs.length+' 条睡眠记录'}</b><p>${demo?'示例模式':'本机保存 · 无需账号'}</p></div></div>${group('记录与作息',[switchRow('moon','自动推测睡眠','后台整理手机使用信号','enabled',data.enabled),action('shield','使用情况访问',data.granted?'已允许 · 可以在系统设置中撤回':'未允许 · 手动记录仍可使用','grant',demo),action('clock','图表时长参考线',short(data.target)+' · 不限制监测时间','plan',demo)])}${group('数据与隐私',[action('download','导出睡眠记录','CSV · 自己选择保存位置','export',demo),action('save','备份数据','JSON · 包含记录和设置','backup',demo),action('restore','恢复备份','从你选择的备份文件恢复','import',demo),switchRow('bug','本地诊断','可选；不上传记录或应用内容','diagnostics',data.diagnostics),action('delete','清空睡眠记录','清空后从现在重新记录','clear',demo,true)])}<p class="muted item" style="font-size:12px;line-height:19px;margin-top:-8px">记录保存在本机。眠迹不读取聊天、照片或屏幕内容；导出或备份后，请妥善保管文件。</p>${group('帮助与关于',[action('mail','问题反馈','反馈信箱 · '+data.feedback.length+' 条记录','feedback',demo),switchRow('refresh','自动检查更新','打开时检查，发现新版自动下载校验','autoUpdate',data.autoUpdate),action('refresh','检查更新','查看当前更新服务状态','update',demo),action('info','估算说明','了解结果的可信度与局限','estimate'),action('open','关于眠迹','使用说明与参考来源','about')])}${demo?'':'<button class="textbtn" data-act="demo" style="width:100%">查看独立示例</button>'}`}
function modal(title,content,footer='<button class="textbtn" data-act="close">关闭</button>'){ $('#form').innerHTML=`<h2>${title}</h2>${content}<footer>${footer}</footer>`;if(!$('#dialog').open)$('#dialog').showModal()}
function close(){pendingRestore=null;++restoreGeneration;$('#dialog').close()}
function capability(title,message){modal(title,`<p>${message}</p>`)}
let pendingRestore=null,restoreGeneration=0;
function downloadDemo(kind){
  if(demo)return toast('请退出示例后导出自己的演示记录。');
  try{const content=kind==='backup'?DemoFiles.backup(data):DemoFiles.csv(data.records),type=kind==='backup'?'application/json;charset=utf-8':'text/csv;charset=utf-8',url=URL.createObjectURL(new Blob([content],{type})),link=document.createElement('a');link.href=url;link.download=`眠迹-网页演示-${kind==='backup'?'备份':'记录'}-${localDate(new Date())}.${kind==='backup'?'json':'csv'}`;document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);toast(kind==='backup'?'已发起演示备份下载，包含明文记录和设置，请妥善保管。':'已发起 CSV 下载，仅包含本浏览器的演示记录。')}catch{toast('文件未生成，记录保持不变。请重试。')}
}
function beginRestore(){
  if(demo)return;pendingRestore=null;const generation=++restoreGeneration;
  modal('恢复备份','<p>只恢复你主动选择的眠迹网页演示备份，文件在本浏览器内读取，不上传。手机备份不能在此恢复。</p><input id="backup-file" type="file" accept=".json,application/json" aria-label="选择演示备份文件">','<button class="textbtn" data-act="close">取消</button>');
  const input=$('#backup-file');input.addEventListener('cancel',()=>{if(generation===restoreGeneration){close();toast('已取消选择，原记录保持不变。')}});
  input.addEventListener('change',async()=>{
    const file=input.files[0];if(!file){close();return}
    try{
      if(file.size>DemoFiles.limit)throw Error('备份文件太大，最多 2 MB。');
      const content=await file.text();if(generation!==restoreGeneration||demo||!$('#dialog').open)return;
      const parsed=DemoFiles.validate(content),additions=DemoFiles.additions(data.records,parsed.records);
      pendingRestore=parsed;
      modal(`恢复 ${parsed.records.length} 条记录？`,`<p>导入记录会合并到本地；同日期已有记录优先保留。作息设置保持当前值，原记录不会被删除。备份中的使用权限不会自动授予。</p><p>仅影响网页演示数据。本次新增 ${additions.length} 条，保留 ${parsed.records.length-additions.length} 条已有同日期记录。</p>`,'<button class="textbtn" data-act="close">取消</button><button class="primary" data-act="restore-confirm">合并恢复</button>');
    }catch(error){if(generation!==restoreGeneration)return;pendingRestore=null;modal('无法恢复备份',`<p>${esc(error.message)}</p><p>原记录和设置保持不变。</p>`,'<button class="textbtn" data-act="close">关闭</button><button class="primary" data-act="import">重新选择</button>')}
  });input.click();
}
function confirmRestore(){
  if(demo||!pendingRestore)return;
  const ids=new Set(data.records.map(r=>r.id)),additions=DemoFiles.additions(data.records,pendingRestore.records).map(r=>({...r,id:ids.has(r.id)?crypto.randomUUID():r.id,source:'备份恢复'}));
  const next={...data,records:data.records.concat(additions).sort((a,b)=>b.end-a.end)};
  try{localStorage.setItem(KEY,JSON.stringify(next))}catch{toast('浏览器未允许保存，恢复未完成，原记录保持不变。');return}
  data=next;close();render();toast(`演示备份已合并，新增 ${additions.length} 条；同日期记录和当前设置已保留。`);
}
$('#dialog').addEventListener('cancel',()=>{pendingRestore=null;++restoreGeneration});
function editor(id){const r=data.records.find(x=>x.id===id);const end=r?new Date(r.end):new Date(new Date().setHours(7,0,0,0)),start=r?new Date(r.start):new Date(+end-data.target*60000);modal(r?'修改与确认记录':'记一晚睡眠',`<p>选好起止日期和时间，跨夜也可以记录。</p><form id="record-form"><input type="hidden" name="id" value="${esc(id||'')}"><label>开始</label><div class="fieldrow"><input name="startDate" type="date" aria-label="开始日期" value="${localDate(start)}" required><input name="startTime" type="time" aria-label="开始时间" value="${clock(+start)}" required></div><label>结束</label><div class="fieldrow"><input name="endDate" type="date" aria-label="结束日期" value="${localDate(end)}" required><input name="endTime" type="time" aria-label="结束时间" value="${clock(+end)}" required></div><div class="forminfo" id="record-info"></div><label>醒来时的感受</label><span id="quality-label" class="muted">一般</span><input name="quality" aria-label="醒来感受" type="range" min="1" max="5" value="${r?.quality||3}"><label for="note">备注（可选）</label><textarea id="note" name="note" maxlength="500" placeholder="例如：昨晚加班、睡前喝了咖啡">${esc(r?.note||'')}</textarea><label class="checkbox"><input name="excluded" type="checkbox" ${r?.excluded?'checked':''}>保留记录，但不计入统计</label></form>`,'<button class="textbtn" data-act="close">取消</button><button class="primary" data-act="save-record">保存记录</button>');validateEditor()}
function validateEditor(){const f=$('#record-form');if(!f)return;const x=Object.fromEntries(new FormData(f)),start=+new Date(x.startDate+'T'+x.startTime),end=+new Date(x.endDate+'T'+x.endTime),m=(end-start)/60000;const error=!Number.isFinite(m)?'请填写完整日期和时间。':m<=0?'结束时间需要晚于开始时间。跨夜记录请分别选择日期。':m>1440?'一条记录最多 24 小时，请核对日期与时间。':end>Date.now()?'结束时间还未到，请选择已经结束的睡眠。':null;$('#record-info').textContent=error||'这段时间共 '+short(Math.trunc(m));$('[data-act="save-record"]').disabled=!!error;$('#quality-label').textContent=['很疲惫','有点疲惫','一般','还不错','精神很好'][+x.quality-1];return{...x,start,end,minutes:Math.trunc(m),error}}
document.addEventListener('input',e=>{if(e.target.closest('#record-form'))validateEditor();if(e.target.id==='target')$('#target-label').textContent='时长目标  '+short(+e.target.value)});
document.addEventListener('click',e=>{const n=e.target.closest('[data-tab],[data-act],[data-edit],[data-range],[data-day],[data-switch],[data-menu]');if(!n)return;scrolls[tab]=$('#page').scrollTop;if(n.dataset.tab!==undefined){tab=+n.dataset.tab;render();return}if(n.dataset.range){days=+n.dataset.range;selected=days-1;render();return}if(n.dataset.day!==undefined){selected=+n.dataset.day;render();return}if(n.dataset.edit){editor(n.dataset.edit);return}if(n.dataset.menu){menu=n.dataset.menu;const r=data.records.find(x=>x.id===menu);modal('记录操作',`<button class="setting" data-act="edit-menu">修改与确认</button><button class="setting" data-act="exclude">${r.excluded?'重新计入统计':'不计入统计'}</button><button class="setting danger" data-act="delete">删除记录</button>`);return}if(n.dataset.switch){data[n.dataset.switch]=!data[n.dataset.switch];persist();render();if(n.dataset.switch==='enabled')toast('网页版只切换演示状态，不读取手机使用事件。');return}const act=n.dataset.act;
if(act==='close')close();else if(act==='add')editor();else if(act==='demo'){demo=true;scrolls.fill(0);render()}else if(act==='exit-demo'){demo=false;scrolls.fill(0);render()}else if(act==='enable'||act==='grant'){if(act==='enable'&&data.granted){data.enabled=true;persist();render()}else capability('使用情况访问','浏览器无法授予 Android 使用情况访问，也不会在后台读取手机使用时间。请在手机 APP 中开启；本页可使用“补记”或“查看独立示例”体验。')}
else if(act==='plan')modal('图表参考线',`<p>仅调整图表参考线，监测不限制开始和结束时刻。</p><label id="target-label">时长目标  ${short(data.target)}</label><input id="target" type="range" aria-label="每日睡眠时长目标，6至10小时" min="360" max="600" step="15" value="${data.target}"><div class="row between muted" style="font-size:11px"><span>6 小时</span><span>10 小时</span></div><p style="margin-top:18px">18–60 岁成人通常至少需要 7 小时睡眠。目标可以按个人情况调整，不代表医学建议。</p>`,'<button class="textbtn" data-act="close">取消</button><button class="primary" data-act="save-plan">保存目标</button>');
else if(act==='save-plan'){data.target=+$('#target').value;persist();close();render()}
else if(act==='clear')modal('清空本机记录？','<p>将删除本机睡眠记录，之后从现在重新记录；此操作无法撤销。</p>','<button class="textbtn" data-act="close">保留</button><button class="primary" data-act="clear-confirm">清空记录</button>');
else if(act==='clear-confirm'){data.records=[];persist();close();render();toast('演示睡眠记录已清空，监测开关保持原状态。')}
else if(act==='save-record'){const x=validateEditor();if(x.error)return;const old=data.records.find(r=>r.id===x.id),r={id:x.id||crypto.randomUUID(),date:localDate(new Date(x.end)),start:x.start,end:x.end,minutes:x.minutes,phoneUse:0,zoneId:Intl.DateTimeFormat().resolvedOptions().timeZone,source:old?.source||'手动',confirmed:true,quality:+x.quality,note:x.note.trim(),excluded:x.excluded==='on',reason:old?'起止时间由你手动确认，按修正后的时长记录。':''};data.records=data.records.filter(a=>a.id!==r.id&&a.date!==r.date).concat(r);persist();close();render();toast('演示记录已保存到本浏览器，与手机数据独立。')}
else if(act==='edit-menu'){close();editor(menu)}else if(act==='exclude'){const r=data.records.find(x=>x.id===menu);r.excluded=!r.excluded;persist();close();render()}else if(act==='delete')modal('删除这条记录？','<p>记录将从本机删除，趋势也会重新计算。此操作无法撤销。</p>','<button class="textbtn" data-act="close">保留</button><button class="primary" data-act="delete-confirm">删除记录</button>');else if(act==='delete-confirm'){data.records=data.records.filter(x=>x.id!==menu);persist();close();render()}
else if(act==='feedback')modal('问题反馈',`<p>反馈信箱 · ${data.feedback.length} 条记录</p><p>网页版演示不会向正式反馈服务发送内容，填写的演示反馈仅保留在本浏览器。</p><textarea id="feedback" maxlength="1500" aria-label="有什么可以更好？" placeholder="有什么可以更好？"></textarea>`,'<button class="textbtn" data-act="close">取消</button><button class="primary" data-act="save-feedback">发送反馈</button>');else if(act==='save-feedback'){let text=$('#feedback').value.trim();if(text.length<3)return toast('请填写 3–1500 字反馈');data.feedback.push({text,at:Date.now()});persist();close();render();toast('仅保存演示反馈，未发送到正式服务。')}
else if(act==='export'||act==='backup')downloadDemo(act);else if(act==='import')beginRestore();else if(act==='restore-confirm')confirmRestore();
else if(act==='update')capability('检查更新','网页不能安装 Android 更新。当前对照版本为眠迹 1.1.2，正式安装和校验由 APP 完成。');
else if(act==='estimate')modal('理解这份睡眠估算','<h3>依据手机使用时间</h3><p>眠迹寻找较长的手机静默区间，按实际关屏与后续使用信号推测休息起止，不限定作息时刻。区间内的手机使用会从估算时长中扣除。</p><h3>可信度不等于准确率</h3><p>信号越完整、边界越清晰，估算参考价值越高。系统记录缺失、关机、阅读或使用其他设备，都可能影响结果。</p><h3>由你确认更可靠</h3><p>你可以修改时间、记录感受，或把一条记录排除统计。确认只表示你认可记录，不代表临床测量。</p><h3>无法监测的内容</h3><p>没有传感器测量，无法识别睡眠阶段、呼吸、真实夜醒或睡眠疾病。这份记录用于作息回顾，不能替代医疗评估。</p>','<button class="textbtn" data-act="close">了解了</button>');else if(act==='about')modal('眠迹','<p>根据手机使用事件估计休息窗口，默认自动记录。推测不等于真实睡眠，可在日记中校正。</p><hr><h3>参考来源</h3><a class="source" href="https://www.cdc.gov/sleep/about/" target="_blank" rel="noopener">CDC · 睡眠与健康 ↗</a><a class="source" href="https://www.nhlbi.nih.gov/health/sleep-deprivation/healthy-sleep-habits" target="_blank" rel="noopener">NIH · 健康睡眠习惯 ↗</a><p>参考资料提供通用知识，不构成诊断或个体治疗方案。</p>');});
document.addEventListener('keydown',e=>{if(e.key==='Escape')close();if(e.key==='Enter'&&(e.target.dataset.day!==undefined||e.target.dataset.edit))e.target.click()});$('#page').addEventListener('scroll',()=>scrolls[tab]=$('#page').scrollTop);render();
window.addEventListener("resize",()=>requestAnimationFrame(()=>{const area=$(".chartarea");if(tab===1&&area)area.innerHTML=chart(daily(records()))}));
