let historyShown=50;
'use strict';
const E=ScoreEngine,$=id=>document.getElementById(id);
let store={current:E.fresh({names:[['演示蓝方'],['演示红方']]}),undo:[],records:[],tournaments:[],players:[],feedback:[],prefs:{awake:true,autoUpdate:true,theme:'redblue',orientation:'auto'}},editing=false,confirmAction=null;
function message(title,body){$('messageTitle').textContent=title;$('messageBody').textContent=body;$('message').showModal();}
function save(){try{const json=JSON.stringify(store);if(window.Native){if(!Native.save(json))throw Error('save');}else localStorage.setItem('yuji-demo-v1',json);$('persist').textContent='比赛自动保存';if(typeof queueSync==='function')queueSync();return true;}catch(e){$('persist').textContent='保存失败 · 请勿关闭';return false;}}
function archive(){if(typeof syncFixture==='function')syncFixture();if(store.current.phase==='finished'){store.records=store.records.filter(r=>r.id!==store.current.id);store.records.unshift(E.copy(store.current));}else store.records=store.records.filter(r=>r.id!==store.current.id);}
function change(f,approved=false){if(!approved&&typeof protectProgress==='function'&&protectProgress(f(E.copy(store.current)),()=>change(f,true)))return;store.undo.push(E.copy(store.current));if(store.undo.length>400)store.undo.shift();store.current=f(store.current);archive();save();render();}
function render(){const s=store.current;document.body.dataset.theme=store.prefs.theme;$('app').classList.toggle('ended',s.phase!=='playing');const order=s.swapped?[1,0]:[0,1];$('boards').append(...order.map(i=>$('panel'+i)));for(let i=0;i<2;i++){$('name'+i).textContent=E.label(s,i);$('score'+i).textContent=s.score[i];$('serve'+i).textContent=s.server===i?(s.mode==='doubles'?'发球队':'发球')+' · '+(s.score[i]%2===0?'右区（双数）':'左区（单数）'):'接发球';$('serve'+i).classList.toggle('serving',s.server===i);$('side'+i).disabled=s.phase!=='playing';$('minus'+i).disabled=s.score[i]===0;$('minus'+i).setAttribute('aria-label',E.label(s,i)+' 减一分');$('side'+i).setAttribute('aria-label',E.label(s,i)+' '+s.score[i]+' 分，点击加一分');}
$('setscore').replaceChildren();s.wins.forEach((n,i)=>{const t=document.createElement('b');t.textContent=n;t.className=i===0?'setA':'setB';if(i===1)$('setscore').append(document.createTextNode(' : '));$('setscore').append(t);$('winsSummary'+i).textContent='已赢 '+n+' 局';});$('sets').style.flexDirection=s.swapped?'row-reverse':'row';
$('modeLabel').textContent=(s.mode==='doubles'?'双打':'单打')+' · '+s.target+' 分 · '+(s.bestOf===3?'三局两胜':'单局');$('gameLabel').textContent='第 '+Math.min(s.games.length+(s.phase==='playing'?1:0),s.bestOf)+' 局';$('status').textContent=s.notice||'上滑加分 · 下滑减分';$('undo').disabled=store.undo.length===0;$('result').hidden=s.phase==='playing';if(s.phase!=='playing'){const winner=s.games[s.games.length-1].winner;$('resultTitle').textContent=E.label(s,winner)+(s.phase==='finished'?' 赢得比赛':' 赢下本局');$('resultScores').textContent=s.games.map(g=>g.score.join(' : ')).join('　 /　');$('next').textContent=s.phase==='finished'?'再来一场':'开始下一局';} rosterOptions();}
function rosterOptions(){$('players').replaceChildren(...store.players.map(n=>{const o=document.createElement('option');o.value=n;return o;}));}
function remember(names){for(const n of names.flat()){if(n&&!/^选手 [AB]$/.test(n)&&!store.players.includes(n))store.players.push(n);}}
function setup(edit=false){editing=edit;const s=store.current;$('setupTitle').textContent=edit?'修改姓名':'新比赛';$('start').textContent=edit?'保存姓名':'开始比赛';$('mode').value=s.mode;$('target').value=s.target;$('bestOf').value=s.bestOf;$('firstServer').value=s.server;$('a1').value=/^选手 [AB]$/.test(s.names[0][0])?'':s.names[0][0];$('b1').value=/^选手 [AB]$/.test(s.names[1][0])?'':s.names[1][0];$('a2').value=s.names[0][1]||'';$('b2').value=s.names[1][1]||'';for(const id of ['mode','target','bestOf','firstServer'])$(id).disabled=edit;$('setupHint').textContent=edit?'比分保持不变，姓名同步更新本场记录。':'姓名可留空，使用默认选手名。开始新比赛会替换当前计分，已完赛记录保留。';toggleDoubles();$('settings').showModal();}
function toggleDoubles(){document.querySelectorAll('.doublefield').forEach(e=>e.hidden=$('mode').value!=='doubles');}
function confirm(title,body,fn){$('confirmTitle').textContent=title;$('confirmBody').textContent=body;confirmAction=fn;$('confirm').showModal();}
function share(text){message('演示比赛摘要',text+'\n\n真实文件导出和系统分享请在 Android 应用中使用。');}
function recordList(){const list=$('recordList');list.replaceChildren();if(!store.records.length){const p=document.createElement('p');p.className='muted';p.textContent='还没有完赛记录。打完一场后会自动出现在这里。';list.append(p);}store.records.slice(0,historyShown).forEach(r=>{const div=document.createElement('div');div.className='record';const title=document.createElement('strong');title.textContent=E.label(r,0)+' vs '+E.label(r,1);const p=document.createElement('p');p.textContent=new Date(r.finished).toLocaleString('zh-CN')+'\n'+r.games.map(g=>g.score.join(' : ')).join(' / ')+'\n胜方：'+E.label(r,r.wins[0]>r.wins[1]?0:1);const b=document.createElement('button');b.className='secondary';b.textContent='导出 / 分享';b.onclick=()=>exportDialog(r);div.append(title,p,b);list.append(div);});if(store.records.length>historyShown){const more=document.createElement('button');more.className='secondary';more.textContent='加载更多 · 共 '+store.records.length+' 场';more.onclick=()=>{historyShown+=50;recordList();};list.append(more);}if(!$('records').open)$('records').showModal();}
function exportDialog(s){let d=$('exportDialog');if(!d){d=document.createElement('dialog');d.id='exportDialog';d.innerHTML='<div class="dialoghead"><h2>导出比赛</h2><button class="close" aria-label="关闭">×</button></div><p class="muted" id="exportName"></p><label>文件格式<select id="exportFormat"><option value="docx">Word 文档（.docx）</option><option value="pptx">PowerPoint 演示（.pptx）</option></select></label><button class="primary" id="exportSave" style="margin-top:18px">保存文件</button><button class="secondary" id="exportShare" style="width:100%;margin-top:12px">分享文件</button><button class="row" id="exportText">分享文字比分 <span>›</span></button>';document.body.append(d);d.querySelector('.close').onclick=()=>d.close();}$('exportName').textContent=E.label(s,0)+' vs '+E.label(s,1)+' · '+(s.phase==='finished'?'已完赛':'进行中');function doExport(mode){if(!window.Native){message('需要 Android 应用','文件导出请在安装后的羽记中使用。');return;}d.close();Native.exportOffice(JSON.stringify(s),$('exportFormat').value,mode);$('status').textContent='正在生成比赛文件…';}$('exportSave').onclick=()=>doExport('save');$('exportShare').onclick=()=>doExport('share');$('exportText').onclick=()=>{d.close();share(E.summary(s));};d.showModal();}
function people(){const list=$('peopleList');list.replaceChildren();for(const n of store.players){const row=document.createElement('div');row.className='row';const span=document.createElement('span');span.textContent=n;const b=document.createElement('button');b.className='secondary';b.textContent='移除';b.setAttribute('aria-label','移除常用选手 '+n);b.onclick=()=>{store.players=store.players.filter(x=>x!==n);save();peopleRender();};row.append(span,b);list.append(row);}if(!store.players.length)list.textContent='还没有常用选手';}
function peopleRender(){people();rosterOptions();}
function scoreAction(i,delta){if(delta>0&&store.current.phase!=='playing'||delta<0&&store.current.score[i]===0)return;change(s=>delta>0?E.add(s,i):E.minus(s,i));if(window.Native)Native.haptic();}
for(let i=0;i<2;i++){let start=null,ignoreClick=false;$('side'+i).onclick=()=>{if(ignoreClick){ignoreClick=false;return;}scoreAction(i,1);};$('minus'+i).onclick=()=>{if(ignoreClick){ignoreClick=false;return;}scoreAction(i,-1);};const panel=$('panel'+i);panel.addEventListener('pointerdown',e=>{if(!e.isPrimary||e.button!==0)return;start={x:e.clientX,y:e.clientY,id:e.pointerId};});panel.addEventListener('pointercancel',()=>{start=null;});panel.addEventListener('pointerup',e=>{if(!start||start.id!==e.pointerId)return;const dy=e.clientY-start.y,dx=e.clientX-start.x;start=null;if(Math.abs(dy)>=45&&Math.abs(dy)>Math.abs(dx)*1.4){ignoreClick=true;scoreAction(i,dy<0?1:-1);setTimeout(()=>{ignoreClick=false;},350);}});}
$('undo').onclick=()=>{if(store.undo.length){const apply=()=>{store.current=store.undo.pop();archive();save();render();};if(typeof protectProgress!=='function'||!protectProgress(store.undo[store.undo.length-1],apply))apply();}};
$('swap').onclick=()=>change(s=>({...s,swapped:!s.swapped,notice:'已交换屏幕位置 · 分数与姓名保持对应'}));$('edit').onclick=()=>setup(true);$('next').onclick=()=>store.current.phase==='gameOver'?change(E.next):setup(false);
$('mode').onchange=toggleDoubles;$('setup').onsubmit=e=>{e.preventDefault();const names=[[$('a1').value.trim()||'选手 A'],[$('b1').value.trim()||'选手 B']];if($('mode').value==='doubles'){for(const [i,id] of [[0,'a2'],[1,'b2']])if($(id).value.trim())names[i].push($(id).value.trim());}const fn=()=>{if(editing)change(s=>({...s,names}));else{archive();store.current=E.fresh({names,mode:$('mode').value,target:Number($('target').value),bestOf:Number($('bestOf').value),server:Number($('firstServer').value)});store.undo=[];}remember(names);save();render();$('settings').close();};if(!editing&&store.current.phase!=='finished'&&(store.current.games.length||store.current.score.some(x=>x)))confirm('开始新比赛？','当前未完赛的比分将被替换。完赛历史和常用选手会保留。',fn);else fn();};
$('confirmYes').onclick=()=>{$('confirm').close();const f=confirmAction;confirmAction=null;if(f)f();};$('confirmCancel').onclick=()=>{$('confirm').close();confirmAction=null;};
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());$('menu').onclick=()=>{$('awake').checked=store.prefs.awake;$('autoUpdate').checked=store.prefs.autoUpdate;$('theme').value=store.prefs.theme;$('orientation').value=store.prefs.orientation;$('tools').showModal();};$('theme').onchange=()=>{store.prefs.theme=$('theme').value;save();render();};$('newMatch').onclick=()=>{$('tools').close();setup(false);};$('share').textContent='导出 / 分享当前比赛　›';$('share').onclick=()=>exportDialog(E.copy(store.current));$('history').onclick=()=>{historyShown=50;recordList();};$('roster').onclick=()=>{people();$('people').showModal();};$('addPlayer').onsubmit=e=>{e.preventDefault();const n=$('playerName').value.trim();if(!n)return;if(!store.players.includes(n))store.players.push(n);$('playerName').value='';save();peopleRender();};
$('awake').onchange=()=>{store.prefs.awake=$('awake').checked;save();if(window.Native)Native.keepAwake(store.prefs.awake);};$('autoUpdate').onchange=()=>{store.prefs.autoUpdate=$('autoUpdate').checked;save();};$('update').onclick=()=>message('更新来源未接入','当前版本 1.0.1。尚未配置可信下载源，暂时无法检查或自动更新。比赛计分不受影响。');
$('scoreTab').onclick=()=>{document.querySelectorAll('dialog[open]').forEach(d=>d.close());};$('playersTab').onclick=()=>{people();$('people').showModal();};
$('help').onclick=()=>message('计分说明','21 分制：先到 21 分且领先 2 分获胜；29 平后先到 30 分获胜。\n15 分模式：领先 2 分获胜，21 分封顶。\n三局两胜：每局结束交换场地；决胜局首次到 11 分（15 分模式为 8 分）时交换。单局模式也会中途换边。\n得分方下一球发球：偶数分从右区、奇数分从左区。双打只提示发球队与发球区，不追踪每位队员轮转。\n撤销可恢复上一分、换边、姓名或下一局。左右位置改变时分数始终跟随同一选手。');
$('feedback').onclick=()=>$('feedbackDialog').showModal();$('feedbackForm').onsubmit=e=>{e.preventDefault();const text=$('feedbackText').value.trim();if(!text)return;store.feedback.push({id:Date.now(),version:'1.0.1',text,status:'local'});store.feedback=store.feedback.slice(-30);if(save()){$('feedbackText').value='';message('已保存到本地','反馈尚未发送。你可以使用“分享本地反馈”交给开发者。');}};$('exportFeedback').onclick=()=>share(store.feedback.length?store.feedback.map(f=>'羽记 '+f.version+' · '+new Date(f.id).toLocaleString('zh-CN')+'\n'+f.text).join('\n\n'):'暂无本地反馈');
window.onNativeExport=msg=>{$('status').textContent=msg;};window.onNativeBack=()=>{const ds=[...document.querySelectorAll('dialog[open]')];if(ds.length){ds[ds.length-1].close();return true;}return false;};window.onNativePause=()=>save();
try{const raw=window.Native?Native.load():localStorage.getItem('yuji-demo-v1');if(raw){const parsed=JSON.parse(raw);if(parsed.current&&Array.isArray(parsed.current.score)&&Array.isArray(parsed.current.names)&&Array.isArray(parsed.records)){store={...store,...parsed,prefs:{...store.prefs,...parsed.prefs}};}else throw Error('state');}}catch(e){message('无法读取上次比赛','保存的数据无法读取。当前从新比赛开始，损坏原件仍保留在应用存储中。');}
const svg=(path)=>'<svg viewBox="0 0 24 24">'+path+'</svg>';
$('menu').innerHTML=svg('<polygon points="20.957,11.118 19.215,12.711 18.938,14.105 19.937,16.243 18.957,17.710 16.599,17.604 15.418,18.394 14.613,20.612 12.882,20.957 11.289,19.215 9.895,18.938 7.757,19.937 6.290,18.957 6.396,16.599 5.606,15.418 3.388,14.613 3.043,12.882 4.785,11.289 5.062,9.895 4.063,7.757 5.043,6.290 7.401,6.396 8.582,5.606 9.387,3.388 11.118,3.043 12.711,4.785 14.105,5.062 16.243,4.063 17.710,5.043 17.604,7.401 18.394,8.582 20.612,9.387"/><circle cx="12" cy="12" r="3"/>');
const icons={undo:'<path d="M8 4 3 9l5 5M3 9h10a6 6 0 0 1 0 12h-3"/>',swap:'<path d="M3 7h17m-5-5 5 5-5 5M21 17H4m5-5-5 5 5 5"/>',edit:'<circle cx="12" cy="6" r="4"/><path d="M4 22v-4c0-8 16-8 16 0v4Z"/>'};
for(const [id,label] of [['undo','撤销'],['swap','换边'],['edit','姓名']])$(id).innerHTML=svg(icons[id])+'<span>'+label+'</span>';
for(let i=0;i<2;i++){$('side'+i).querySelector('.addlabel').innerHTML=svg('<path d="m4 16 8-8 8 8"/>')+'<span>加分</span>';$('minus'+i).innerHTML=svg('<path d="m4 8 8 8 8-8"/>')+'<span>减分</span>';}
render();if(window.Native){Native.keepAwake(store.prefs.awake);Native.orientation(store.prefs.orientation);}document.documentElement.classList.add('ready');document.addEventListener('visibilitychange',()=>{if(document.hidden)save();});

function setOrientation(value){store.prefs.orientation=value;save();$('orientation').value=value;if(window.Native)Native.orientation(value);else window.parent.postMessage({type:'yuji-demo-orientation',value},location.origin);}
$('orientation').onchange=()=>setOrientation($('orientation').value);$('rotate').onclick=()=>setOrientation(innerWidth>innerHeight?'portrait':'landscape');
