'use strict';
const T=TournamentEngine;let selectedEvent='',selectedFixture='',importPayload=null,importRows=[];
function el(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;}
function closeAll(){document.querySelectorAll('dialog[open]').forEach(d=>d.close());}
function currentEvent(){return (store.tournaments||[]).find(t=>t.id===selectedEvent);}
function displayDue(s){return s?s.replace('T',' '):'时间待安排';}
function showEvents(){closeAll();$('eventList').replaceChildren();if(!(store.tournaments||[]).length)$('eventList').append(el('p','还没有赛事。可导入 Word / Excel，或新建对阵。','muted'));for(const t of store.tournaments||[]){const b=el('button',t.name+' · '+t.fixtures.filter(f=>f.result||f.bye).length+'/'+t.fixtures.length+' 场','row');b.onclick=()=>{selectedEvent=t.id;renderEvent();};$('eventList').append(b);}$('events').showModal();}
function renderEvent(){const t=currentEvent();if(!t)return;closeAll();$('eventTitle').textContent=t.name;$('eventSubtitle').textContent=(t.type==='knockout'?'单淘汰 · 胜者晋级':t.type==='roundrobin'?'循环赛 · 每两方对战一次':'自定义对战日程')+' · '+(t.mode==='doubles'?'双打':'单打');$('scheduleList').replaceChildren();const fixtures=t.fixtures.slice().sort((a,b)=>(a.due||'9999').localeCompare(b.due||'9999')||a.round-b.round||a.index-b.index);for(const f of fixtures){const row=el('button',undefined,'fixture row');const a=el('div');a.append(el('small',displayDue(f.due)+(f.court?' · '+f.court:''),'muted'),el('strong',(f.teams[0]||'待上轮胜者')+'  VS  '+(f.teams[1]||(f.bye?'轮空':'待上轮胜者'))));const result=f.live?'进行中 · '+f.live.score.join(':'):f.bye?'轮空晋级':f.result?'胜：'+T.winner(f)+' · '+(f.result.wins||[]).join(':'):'待赛';a.append(el('small','第 '+f.round+' 轮 · '+result,'muted'));row.append(a,el('span','›'));row.onclick=()=>editFixture(f.id);$('scheduleList').append(row);}
const bracket=$('bracket');bracket.replaceChildren();if(t.type==='knockout'){const rounds=Math.max(...t.fixtures.map(f=>f.round));for(let r=1;r<=rounds;r++){const col=el('section',undefined,'bracketcol');col.append(el('h3',r===rounds?'决赛':'第 '+r+' 轮'));const cards=el('div',undefined,'bracketcards');for(const f of t.fixtures.filter(f=>f.round===r)){const card=el('button',undefined,'bracketmatch');card.append(el('small','#'+f.round+'.'+f.index+' · '+displayDue(f.due),'muted'));f.teams.forEach((name,i)=>{const line=el('div',undefined,'bracketteam'+((f.result&&f.result.winner===i)||f.bye&&name?' won':''));line.append(el('span',name||(f.bye?'轮空':'上轮胜者')),el('b',f.result?String((f.result.wins||[])[i]??''):'–'));card.append(line);});card.dataset.fixture=f.id;card.onclick=()=>editFixture(f.id);cards.append(card);}col.append(cards);bracket.append(col);}$('bracketHint').textContent='向左右滑动可看全部轮次；有胜者的场次用蓝色标出，晋级关系按轮次连接。';}else{$('bracketHint').textContent=t.type==='roundrobin'?'按胜场、净胜分排序；同分时暂按姓名排序。':'自定义日程未指定晋级关系，显示对战结果统计。';const table=el('table',undefined,'standings');const head=el('tr');['选手 / 队伍','胜','负','场次','净胜分'].forEach(x=>head.append(el('th',x)));table.append(head);for(const r of T.standings(t)){const tr=el('tr');[r.name,r.win,r.loss,r.played,r.for-r.against].forEach(x=>tr.append(el('td',String(x))));table.append(tr);}bracket.append(table);}$('eventDetail').showModal();requestAnimationFrame(drawBracket);}
function editFixture(id){const t=currentEvent(),f=t.fixtures.find(x=>x.id===id);selectedFixture=id;$('fixtureTitle').textContent=(f.teams[0]||'待定')+' vs '+(f.teams[1]||'待定');$('fixtureDue').value=f.due||'';$('fixtureCourt').value=f.court||'';$('fixtureWinner').replaceChildren(el('option','尚未完赛'));$('fixtureWinner').firstChild.value='';f.teams.forEach((n,i)=>{const o=el('option',n||'待定');o.value=String(i);$('fixtureWinner').append(o);});$('fixtureWinner').value=f.result?String(f.result.winner):'';$('fixtureWinsA').value=f.result?.wins?.[0]??0;$('fixtureWinsB').value=f.result?.wins?.[1]??0;$('playFixture').disabled=f.bye||!f.teams.every(Boolean);$('fixtureNote').textContent=f.bye?'此方轮空，自动晋级。':f.sources.length?'对阵来自上轮胜者；修改胜方会修正后续对阵并清除受影响的后续结果。':'可设置时间、场地，或进入计分。';$('fixtureEdit').showModal();}
function eventSave(){const t=currentEvent(),f=t.fixtures.find(x=>x.id===selectedFixture);f.due=$('fixtureDue').value;f.court=$('fixtureCourt').value.trim();const w=$('fixtureWinner').value;const a=Number($('fixtureWinsA').value),b=Number($('fixtureWinsB').value);if(w!==''&&(a===b||Number(w)!==(a>b?0:1))){message('结果不一致','请填写不同的双方局数，并选择局数较多的一方为胜方。');return;}const apply=()=>{T.result(t,f.id,w===''?null:{winner:Number(w),wins:[a,b],games:f.result&&f.result.winner===Number(w)&&f.result.wins?.[0]===a&&f.result.wins?.[1]===b?f.result.games||[]:[]});save();$('fixtureEdit').close();renderEvent();};const affected=T.descendants(t,f.id).filter(x=>x.result);if(affected.length&&(!f.result||String(f.result.winner)!==w))confirm('修正胜方与后续对阵？','将清除 '+affected.length+' 场受影响的后续结果；原计分历史仍保留。',apply);else apply();}
function startFixture(){const t=currentEvent(),f=t.fixtures.find(x=>x.id===selectedFixture);if(!f.teams.every(Boolean)||f.bye)return;const run=()=>{closeAll();archive();const names=f.teams.map(n=>t.mode==='doubles'?n.split(/\s*[/／、]\s*/).filter(Boolean).slice(0,2):[n]);store.current={...E.fresh({names,mode:t.mode,target:21,bestOf:t.bestOf||3}),eventId:t.id,fixtureId:f.id};store.undo=[];remember(names);save();render();};if(store.current.phase!=='finished'&&(store.current.games.length||store.current.score.some(Boolean)))confirm('切换到这场对战？','将替换当前未完赛计分。已完赛记录保留。',run);else run();}
function syncFixture(){const s=store.current;if(!s.eventId)return;const t=(store.tournaments||[]).find(x=>x.id===s.eventId),f=t?.fixtures.find(x=>x.id===s.fixtureId);if(!f)return;if(s.phase==='finished')T.result(t,f.id,{winner:s.wins[0]>s.wins[1]?0:1,wins:s.wins.slice(),games:E.copy(s.games)});else {if(f.result)T.result(t,f.id,null);f.live={score:s.score.slice(),wins:s.wins.slice(),phase:s.phase};t.updated=Date.now();}if(s.phase==='finished')delete f.live;}
function buildEvent(){const names=$('eventNames').value.split(/\r?\n/).map(n=>n.trim()).filter(Boolean);try{const t=T.create($('newEventName').value.trim(),$('eventType').value,names,$('eventMode').value);t.bestOf=Number($('eventBestOf').value);let start=$('eventStart').value;const minutes=Math.max(1,Number($('eventMinutes').value)||30);if(start){const date=new Date(start);t.fixtures.filter(f=>!f.bye).forEach((f,i)=>{const d=new Date(date.getTime()+minutes*60000*i);f.due=new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);});}store.tournaments.push(t);selectedEvent=t.id;remember(t.participants.map(n=>[n]));save();renderEvent();}catch(e){message('无法创建赛事',e.message);}}
function openImport(){if(window.Native){Native.importFile();}else{$('webImport').click();}}
window.onImportError=msg=>message('未能导入',msg);
window.onNativeImport=data=>{importPayload=data;if(data.text)importPayload.sheets=[{name:'文本 / CSV',rows:T.parseCSV(data.text)}];$('importFileName').textContent=data.name||'导入文件';$('importSheets').replaceChildren(...data.sheets.map((s,i)=>{const o=el('option',s.name);o.value=String(i);return o;}));importSheet();$('importDialog').showModal();};
function importSheet(){importRows=importPayload.sheets[Number($('importSheets').value)].rows.filter(r=>r.some(v=>String(v).trim()));const g=T.guess(importRows);$('importHeader').checked=g.header;$('importStart').value=g.row+1;const fields=['a','b','date','time','court','round'];const row=importRows[g.row]||[];for(const k of fields){const sel=$('map_'+k);sel.replaceChildren();const none=el('option','不使用');none.value='-1';sel.append(none);for(let i=0;i<Math.max(row.length,...importRows.slice(0,20).map(r=>r.length));i++){const o=el('option',(g.header?String(row[i]||''):'')+' · 第 '+(i+1)+' 列');o.value=String(i);sel.append(o);}sel.value=String(g.map[k]??-1);}$('importKind').value=g.map.b>=0?'schedule':'knockout';previewImport();}
function mappedRows(){const start=Math.max(0,Number($('importStart').value)-1)+($('importHeader').checked?1:0);return importRows.slice(start).map((row,i)=>{const o={source:i+start+1};for(const k of ['a','b','date','time','court','round'])o[k]=row[Number($('map_'+k).value)]||'';o.due=T.date(o.date,o.time);return o;});}
function previewImport(){const rows=mappedRows();const preview=$('importPreview');preview.replaceChildren();const table=el('table',undefined,'standings');const h=el('tr');['行','A方 / 名单','B方','时间','场地'].forEach(s=>h.append(el('th',s)));table.append(h);for(const r of rows.slice(0,20)){const tr=el('tr');[r.source,r.a,r.b,r.due||'待设置',r.court].forEach(s=>tr.append(el('td',String(s))));table.append(tr);}preview.append(table);const invalid=rows.filter(r=>!String(r.a).trim()||$('importKind').value==='schedule'&&(!String(r.b).trim()||r.a===r.b)).length;const uncertain=rows.filter(r=>(r.date||r.time)&&!r.due).length;$('importSummary').textContent='识别 '+rows.length+' 行；缺少或冲突姓名 '+invalid+' 行不会导入；未识别日期 '+uncertain+' 行保留为时间待设置。预览前20行，确认才保存。';}
function commitImport(){const rows=mappedRows(),kind=$('importKind').value;let t;try{if(kind==='schedule'){const valid=rows.filter(r=>String(r.a).trim()&&String(r.b).trim()&&r.a!==r.b);if(!valid.length)throw Error('没有有效对阵，请检查双方姓名列');t={id:Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,8),name:$('importEventName').value.trim()||importPayload.name,type:'schedule',mode:$('importMode').value,bestOf:3,participants:[...new Set(valid.flatMap(r=>[String(r.a).trim(),String(r.b).trim()]))],fixtures:valid.map((r,i)=>({...T.fixture([String(r.a).trim(),String(r.b).trim()],Number(r.round)||1,i+1),due:r.due,court:String(r.court)})),updated:Date.now()};}else t=T.create($('importEventName').value.trim()||importPayload.name,kind,rows.map(r=>String(r.a)),$('importMode').value);store.tournaments.push(t);selectedEvent=t.id;remember(t.participants.map(n=>[n]));save();renderEvent();}catch(e){message('无法导入',e.message);}}
function appendFixture(){const a=$('manualA').value.trim(),b=$('manualB').value.trim();if(!a||!b||a===b){message('检查对阵姓名','请填写两个不同的选手或队伍名称。');return;}let t=currentEvent();if(!t||t.type!=='schedule'){t={id:Date.now().toString(36),name:'自定义对战日程',type:'schedule',mode:$('manualMode').value,bestOf:3,participants:[],fixtures:[],updated:Date.now()};store.tournaments.push(t);selectedEvent=t.id;}const f=T.fixture([a,b],1,t.fixtures.length+1);f.due=$('manualDue').value;f.court=$('manualCourt').value.trim();t.fixtures.push(f);t.participants=[...new Set([...t.participants,a,b])];save();renderEvent();}
$('eventsTab').onclick=showEvents;$('newEvent').onclick=()=>{$('eventNames').value=store.players.join('\n');$('eventCreate').showModal();};$('createEvent').onsubmit=e=>{e.preventDefault();buildEvent();};$('importEvent').onclick=openImport;$('importSheets').onchange=importSheet;for(const id of ['importHeader','importStart','importKind','map_a','map_b','map_date','map_time','map_court','map_round'])$(id).onchange=previewImport;$('importCommit').onclick=commitImport;$('fixtureForm').onsubmit=e=>{e.preventDefault();eventSave();};$('playFixture').onclick=startFixture;$('eventBack').onclick=showEvents;$('addFixture').onclick=()=>$('manualFixture').showModal();$('manualForm').onsubmit=e=>{e.preventDefault();appendFixture();};
$('webImport').onchange=async()=>{const f=$('webImport').files[0];if(!f)return;if(!/\.(csv|txt|tsv)$/i.test(f.name)){message('请在 Android 中导入','Word 与 Excel 识别使用安装后的应用，网页预览支持 CSV / TXT。');return;}onNativeImport({name:f.name,text:await f.text()});};

function drawBracket(){const t=currentEvent(),root=$('bracket');if(!t||t.type!=='knockout'||!$('eventDetail').open)return;root.querySelector('.bracketlines')?.remove();const ns='http://www.w3.org/2000/svg',svg=document.createElementNS(ns,'svg'),bounds=root.getBoundingClientRect();svg.setAttribute('class','bracketlines');svg.setAttribute('width',root.scrollWidth);svg.setAttribute('height',root.scrollHeight);for(const f of t.fixtures){const dest=root.querySelector('[data-fixture="'+f.id+'"]');if(!dest)continue;const d=dest.getBoundingClientRect();for(const source of f.sources||[]){const from=root.querySelector('[data-fixture="'+source+'"]');if(!from)continue;const a=from.getBoundingClientRect(),x1=a.right-bounds.left,y1=a.top+a.height/2-bounds.top,x2=d.left-bounds.left,y2=d.top+d.height/2-bounds.top;const path=document.createElementNS(ns,'path');path.setAttribute('d',`M${x1} ${y1} H${(x1+x2)/2} V${y2} H${x2}`);path.setAttribute('fill','none');path.setAttribute('stroke',T.winner(t.fixtures.find(x=>x.id===source))?'#2478cf':'#bdcadb');path.setAttribute('stroke-width','2');svg.append(path);}}root.prepend(svg);}
window.addEventListener('resize',()=>requestAnimationFrame(drawBracket));
function protectProgress(next,apply){const s=store.current,t=store.tournaments.find(x=>x.id===s.eventId),f=t?.fixtures.find(x=>x.id===s.fixtureId);if(f?.result&&T.descendants(t,f.id).some(x=>x.result)&& (next.phase!=='finished'||(next.wins[0]>next.wins[1]?0:1)!==f.result.winner)){confirm('修正已晋级比赛？','这会清除受影响的后续结果。原计分历史保留。',apply);return true;}return false;}
