(function(root){'use strict';const copy=x=>JSON.parse(JSON.stringify(x)),uid=()=>Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,8);
function create(name,type,participants,mode='singles'){const t={id:uid(),name:name||'羽毛球赛事',type,mode,participants:[...new Set(participants.map(s=>s.trim()).filter(Boolean))],fixtures:[],updated:Date.now()};if(t.participants.length<2)throw Error('至少需要两位选手或两支队伍');if(type==='knockout'){let size=2;while(size<t.participants.length)size*=2;let first=[];const byes=size-t.participants.length;let cursor=0;for(let i=0;i<size/2;i++){let teams=i<byes?[t.participants[cursor++],null]:[t.participants[cursor++],t.participants[cursor++]];const f=fixture(teams,1,i+1);f.bye=teams[1]===null;t.fixtures.push(f);first.push(f);}let prev=first,r=2;while(prev.length>1){const next=[];for(let i=0;i<prev.length;i+=2){const f=fixture(['',''],r,next.length+1);f.sources=[prev[i].id,prev[i+1].id];next.push(f);t.fixtures.push(f);}prev=next;r++;}recompute(t);}else if(type==='roundrobin'){let circle=t.participants.slice();if(circle.length%2)circle.push(null);for(let r=1;r<circle.length;r++){for(let i=0;i<circle.length/2;i++){const a=circle[i],b=circle[circle.length-1-i];if(a&&b)t.fixtures.push(fixture([a,b],r,i+1));}circle.splice(1,0,circle.pop());}}return t;}
function fixture(teams,round=1,index=1){return {id:uid(),teams,round,index,due:'',court:'',result:null,sources:[],bye:false};}
function winner(f){return f.bye?f.teams.find(Boolean):f.result?f.teams[f.result.winner]:'';}
function recompute(t){for(const f of t.fixtures){if(f.sources&&f.sources.length){const teams=f.sources.map(id=>winner(t.fixtures.find(x=>x.id===id))||'');if(teams.some((s,i)=>s!==f.teams[i])){f.result=null;delete f.live;f.teams=teams;}}}t.updated=Date.now();return t;}
function descendants(t,id){const out=[];let ids=[id];for(const f of t.fixtures){if(f.sources&&f.sources.some(x=>ids.includes(x))){out.push(f);ids.push(f.id);}}return out;}
function result(t,id,value){const f=t.fixtures.find(x=>x.id===id);if(!f)throw Error('场次不存在');if(value&&(!f.teams[0]||!f.teams[1]))throw Error('双方未确定，不能录入结果');f.result=value;recompute(t);return t;}
function standings(t){const rows=t.participants.map(name=>({name,played:0,win:0,loss:0,for:0,against:0}));for(const f of t.fixtures)if(f.result&&!f.bye){f.teams.forEach((n,i)=>{const r=rows.find(x=>x.name===n);if(!r)return;r.played++;if(f.result.winner===i)r.win++;else r.loss++;for(const g of f.result.games||[]){r.for+=g.score[i];r.against+=g.score[1-i];}});}return rows.sort((a,b)=>b.win-a.win||(b.for-b.against)-(a.for-a.against)||a.name.localeCompare(b.name,'zh-CN'));}
function parseCSV(text){const lines=text.replace(/^\ufeff/,'').split(/\r?\n/);const first=lines.find(s=>s.trim())||'';const sep=first.includes('\t')?'\t':first.includes(',')?',':first.includes(';')?';':null;if(!sep)return lines.filter(s=>s.trim()).map(s=>[s.trim()]);const out=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++;}else quoted=!quoted;}else if(c===sep&&!quoted){row.push(cell.trim());cell='';}else if(c==='\n'&&!quoted){row.push(cell.trim());if(row.some(Boolean))out.push(row);row=[];cell='';}else if(c!=='\r')cell+=c;}row.push(cell.trim());if(row.some(Boolean))out.push(row);return out;}
function date(value,time=''){let s=String(value||'').trim();if(/^\d+(\.\d+)?$/.test(s)&&Number(s)>20000){const d=new Date((Number(s)-25569)*86400000);s=d.toISOString().slice(0,16);}s=s.replace(/[年/.]/g,'-').replace(/月/g,'-').replace(/日/g,'').replace(' ','T');const m=s.match(/^(\d{4})-(\d{1,2})-(\d{1,2})(?:T(\d{1,2}):(\d{2}))?/);if(!m)return '';let hh=m[4]||'00',mm=m[5]||'00';if(time){let z=String(time);if(/^0?\.\d+$/.test(z)){const minutes=Math.round(Number(z)*1440);z=String(Math.floor(minutes/60)).padStart(2,'0')+':'+String(minutes%60).padStart(2,'0');}const h=z.match(/(\d{1,2}):(\d{2})/);if(h){hh=h[1];mm=h[2];}}return m[1]+'-'+m[2].padStart(2,'0')+'-'+m[3].padStart(2,'0')+'T'+hh.padStart(2,'0')+':'+mm;}
function guess(rows){const aliases={a:['a方','甲方','选手a','队伍a','队员a','选手1','队伍1','姓名','选手','队伍','参赛者','team a','player a'],b:['b方','乙方','选手b','队伍b','队员b','选手2','队伍2','对手','team b','player b'],date:['日期','比赛日期','date','开始时间','比赛时间','对战时间'],time:['时间','时刻','time'],court:['场地','球场','court'],round:['轮次','轮数','round']};let best={header:false,row:0,map:{a:0,b:-1,date:-1,time:-1,court:-1,round:-1}},max=0;for(let r=0;r<Math.min(rows.length,10);r++){const map={a:-1,b:-1,date:-1,time:-1,court:-1,round:-1};let score=0;rows[r].forEach((v,i)=>{const h=String(v).trim().toLowerCase().replace(/\s+/g,' ');for(const [key,list] of Object.entries(aliases))if(list.includes(h)){map[key]=i;score++;}});if(score>max){max=score;best={header:true,row:r,map};}}if(best.map.a<0)best.map.a=0;return best;}
const api={create,fixture,winner,recompute,descendants,result,standings,parseCSV,date,guess,copy};root.TournamentEngine=api;if(typeof module!=='undefined')module.exports=api;
})(typeof globalThis!=='undefined'?globalThis:this);
